### ISSUE TITLE
Admin Menu Tree Page View plugin uses 70 queries in WP Admin

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1017]
Is there another plugin that is similar that doesn't use as many queries? Nebula's documentation has more menus than a typical site will have, but there should be a more optimized way to query.

**Comment by rubengc** [comment]
This plugin looks good but I am not a fan of overload admin because this will affect frontend performance

**Comment by chrisblakley** [comment]
Yeah, my solution is generally to only install this plugin when needed. I could probably just close this issue as it isn't necessarily Nebula-specific.
