### ISSUE TITLE
Update the look/feel of the footer on Nebula

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1135]
Update the footer for a better looking one.

**Comment by rubengc** [comment]
But, do you mean the `footerlinks` area or `copyright` area?

I love current `copyright` area

**Comment by chrisblakley** [comment]
Actually, I could probably close this as I took care of it when I updated the new documentation.

Basically going from this:

![screen shot 2017-01-21 at 11 49 21 am](https://cloud.githubusercontent.com/assets/6349678/22176047/af58c98c-dfcf-11e6-9248-cd19a3cd2d72.png)

to this:

![screen shot 2017-01-21 at 11 49 04 am](https://cloud.githubusercontent.com/assets/6349678/22176048/b289007c-dfcf-11e6-85c1-39ccad794690.png)

**Comment by rubengc** [comment]
New footer looks good!

Do you want on customizer show an option to set footer text?

**Comment by chrisblakley** [comment]
I'd leave that up to you if you think it'd be useful (since I never use the Cusomizer myself). What's not shown in the screenshot above is there is a Widget section above the navigation, and I am actually playing around with keeping the footer search in there somewhere too.

**Comment by rubengc** [comment]
I am not lover of add multiple search inputs in page

Normally I reserve footer for small notes like copyright and, on ecommerces, notice about If prices includes taxes

I reserve more advance features on footer widget area

Anyway I do not know how the new footer was build, but I recommend to keep It with a row with a col-12 and text centered to allow override with more columns without need to add a lot of css

On my PR I will remove the footer logo and search input reference and move the footer text to the site identity section

**Comment by rubengc** [comment]
How you keep the search input I recommend to split footer in two columns, one with copyright text and the another one with the input and this column with class `.text-right` (a utility class of bootstrap)

Also to fix search input icon unalignment you need to change this lines:
```css
.borderimage form.nebula-search-iconable:before {
    top: 9px;
    left: 8px;
}
```
