### ISSUE TITLE
More PHP optimization research

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1141]
Using Query Monitor, I can test the Page Generation Time specifically on the server-side. I want to list slow functionality in Nebula to try to optimize further.
- SCSS (when not re-compiling) appears to take about 0.3s (expected this to be higher).
- Weather detection (with expired transient) takes about 0.1s.
- IP Geolocation appears to take less than 0.03s.
- Visitors DB appears to take roughly 3-4s (appears to all be on Hubspot CRM functionality)!
- Domain blacklist seems to take less than 0.04s.
- Device Detector seems to take between 0.3-0.6s.
- As a note, the nebula_extras plugin adds about 0.3s to this timer, too.

Total page generation time for Nebula ranges anywhere from 1-3 seconds typically, but I've seen it as high as 6-9 seconds on occasion.

For reference, twentysixteen comes in at less than 1s.

After tonight's testing, I feel like there is still about 0.5s hiding somewhere within Nebula.

**Comment by chrisblakley** [comment]
Enabled caching option in Device Detector to improve speed by 0.3-0.4s.

**Comment by chrisblakley** [comment]
Maybe for SCSS, we store each file's last modification time to a transient and read from that (when available) instead of looping through each file itself and reading the `filemtime()`.

**Comment by chrisblakley** [comment]
Visitors DB Timings:

- `new_or_returning_visitor()` = 1.6s
- `nebula_update_visitor()` = 1.6s (likely due to `check_if_known()`)

For reference, here are the timing functions I'm using:
```$nebula_debug_start_time = microtime(true);```

```echo "Elapsed Nebula Debug time was: " . number_format((microtime(true)-$nebula_debug_start_time), 6, '.', '') . " seconds.<br/>";```

**Comment by chrisblakley** [comment]
Thoughts to improve Hubspot functionality:

- Pull down all the data from the contact and check each property against the local DB entry, then only push the needed properties back to Hubspot
- Instead of pushing all known properties to Hubspot, only push the default properties.
- "Manually" sync Hubspot data through the Visitors DB admin page.

**Comment by chrisblakley** [comment]
Benchmarks to shoot for (with same plugins, front page only):
- **twentysixteen**: 0.61-1.05s
- **twentythirteen**: 0.51-0.78s
- **twentytwelve**: 0.50-0.68s
- **Nebula v4.3.6**: 0.86-1.04s

So there is between 0.2-0.5s somewhere in Nebula that could be improved...

**Comment by chrisblakley** [comment]
Comparisons to the Nebula Minimum Install on the same server (note: version numbers are practically identical in this case):

- **Nebula v4.6.18 (Min)**: 0.30-0.61s
- **Nebula v4.6.21**: 1.4-1.65s

So there is about 1 second difference between the minimum install and the full install. Full install has lots of remote resources (even on the server-side).

Note: Most of our projects will likely be closer to the minimum install than full (most don't use features like Visitor DB, Weather, IP Geolocation, or even the Device Detector).

**Comment by rubengc** [comment]
About optimization, I am getting a big load time from social buttons

I see some plugins on wordpress that add this feature with more options and with more customizable options, probably is time to delegate this functionality to a third party plugin

**Comment by chrisblakley** [comment]
I've got Nebula (even with big features enabled) down to 0.5-0.7s now. I'm going to close this unless new memory leaks or slow functions are discovered.
