### ISSUE TITLE
Move all the Bootstrap shortcode docs to the same page

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1147]
Instead of using 3 pages with similar examples, just list them all on the same page.

**Comment by chrisblakley** [comment]
Now that we are separating docs by function name, this will not be possible. However, the "showcase" for these can have them all combined and only need to use one... That is, if we use a showcase for this at all.

**Comment by rubengc** [comment]
About bootstrap shortcodes, have you think on derivate this to a third party plugin?

There are some bootstrap specific shortcode plugins but check this one:
https://es.wordpress.org/plugins/shortcodes-ultimate
