### ISSUE TITLE
It's time to switch from W3 TotalCache to something else.

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1157]
The [latest XSS vulnerability](https://secupress.me/w3-total-cache-vulnerable-xss-high-risk/) was the tipping point. I had been falling out of love with this plugin for the last few years anyway.

[Autoptimize](https://wordpress.org/plugins/autoptimize/) was recommended, but it only minifies- it would need to be coupled with a caching plugin too.

Not interested in WP Super Cache.

Others to look into:
- [WP Rocket](https://wp-rocket.me/pricing/) (Best, but paid. $199 for unlimited sites)
- [Comet Cache](https://wordpress.org/plugins/comet-cache/)
- [Hyper Cache](https://wordpress.org/plugins/hyper-cache/)
- [Cache Enabler](https://wordpress.org/plugins/cache-enabler/)
- [WP Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/)

What I'm looking for:
- Ideally free
- Options to minify and cache
- No conflicts with other plugins
- Ideally doesn't need to rewrite htaccess files (reduce risk of 500 errors)

Open to additional ideas.

**Comment by rubengc** [comment]
WP Fastest Cache looks good

**Comment by rubengc** [comment]
I tested WP Super Cache yesterday and It got awesome results

https://wordpress.org/plugins/wp-super-cache/

**Comment by chrisblakley** [comment]
I've played with Super Cache before and while it caches really well, I ran into issues where clearing the cache was difficult and we ended up fighting cached resources constantly. Maybe it's gotten better, so I'll give it another try soon.

**Comment by chrisblakley** [comment]
Looks like Super Cache will be launching a major update soon so i might give it a try then. I didn't realize it was partially maintained by Automattic... that's enough for a second try at least.

**Comment by chrisblakley** [comment]
https://wordpress.org/plugins/hummingbird-performance/

Just saw this one tonight... looks like it works with other tools not as a replacement though

**Comment by chrisblakley** [comment]
The "something else" that I've been relying on lately is Nebula itself. With huge improvements to prefetch and service workers (as well as general optimization) the caching plugin hasn't been as much of a need.

Nebula still bundles W3 Total Cache, and I'm still open to switching if I can see some compelling evidence of **what** to switch to, but I'm going to close this issue for now.
