### ISSUE TITLE
Fresh theme install porblem

### ISSUE THREAD

**Issue by borisiceman** [chrisblakley/Nebula#1167]
Fatal error: 'break' not in the 'loop' or 'switch' context ...\wp-content\themes\Nebula-master\functions\nebula_utilities.php on line 2545

**Comment by chrisblakley** [comment]
Thanks for reporting this. I'll look into it ASAP.

**Comment by chrisblakley** [comment]
This has been fixed. I haven't had an opportunity to get in depth with PHP7 yet, so I appologize for any hiccups there.
