### ISSUE TITLE
Expand CRM support to include Hubspot, Salesforce, Marketo and SharpSpring

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1182]
Expand CRM support to include Salesforce and Marketo too (instead of just Hubspot CRM).

Currently Nebula Visitor DB functions are found in `nebula_utilities.php`.

Some implementation ideas:

- Create a "crm" directory in `functions` directory that will contain a PHP file for each CRM.
 - Not all CRM integrations will be PHP...
- Create a `crm.php` file and do logic in there.
- Create a `crm.js` file and call it from `crm.php` (or `functions.php`) and control all AJAX and PHP from there.
 - If we do this, I still need to tie it into `nv()`, so that function would probably need to move into this new file too.

Ideally with Hubspot Marketing, and Magento (and probably Salesforce too) we would not need the PHP files at all... Ideally we'd include all of the checks and sends right from main.js.

Similar to the Facebook events, we'd just check if each is enabled and run the appropriate functions for the one(s) that are.

May need to separate contact properties vs. events with 2 different functions (or pass different parameters like GA does).
```js
nv('send', 'event', 'CTA Click');
nv('send', 'property', 'Job Title', 'CEO');
nv('get', 'property', 'Job Title'); //Would this need the "property" parameter at all or can we assume that get only uses properties?
```

**Comment by chrisblakley** [comment]
# Hubspot CRM
Note: This is already implemented, but there are still some concerns and questions I have.

Documentation and other info will go here.

**Comment by chrisblakley** [comment]
# Salesforce

Documentation and other info will go here.

**Comment by chrisblakley** [comment]
# Marketo

Likely will use "Web Personalization". Documentation here:
http://developers.marketo.com/javascript-api/web-personalization/

We will tie into the custom data events with this JavaScript function:
http://developers.marketo.com/javascript-api/web-personalization/custom-data-events/

Marketo integration will be JavaScript, so my first thought is to tie it into `nv()` in main.js.

**Comment by chrisblakley** [comment]
# Other CRMs

If there is info regarding other CRM integration, I'll add documentation and other info here.

**Comment by rubengc** [comment]
I think hubspot integration (like woocommerce and google analytics) should go out of nebula and keep them as extensions

Or make something like Unyson framework (it has built-in extensions with a view to active deactive them)

**Comment by chrisblakley** [comment]
I could see this CRM support moving to some kind of extension in the future. Right now the Nebula Visitor DB does have an enable/disable toggle which is where the current Hubspot integration lives. The current CRM functionality (as well as Visitor DB) is still in its infancy, so unless/until it gets stronger, I'll probably leave it bundled with the theme.

Nebula WooCommerce support automatically enabled/disabled depending if the WooCommerce plugin is active.

Google Analytics is a cornerstone of Nebula and one of the strongest reasons it stands out from other starter themes, so I don't foresee that aspect leaving the core theme functionality.

**Comment by rubengc** [comment]
Probably analytics and visitors are a good feature to keep in

When we finish to implement OOP, we could create a woocommerce integration (like current one to EDD)

**Comment by chrisblakley** [comment]
Consider replacing the `nv()` function (yet again) with a hook system so that detections can be hooked into by other tools (regardless of whether we're using Hubspot, Marketo, Salesforce, or something else).

Then, the `nv()` function itself could be reimplemented to listen for those hook triggers. Either within a crm.js file or some other method.

**Comment by chrisblakley** [comment]
[SharpSpring](https://help.sharpspring.com/hc/en-us/articles/115003079951-Understanding-SharpSpring-API-Schema) seems promising in that they offer more features at their base price compared to Marketo and Hubspot. I'm trying to find if their API is server-side only or if it has JavaScript support too.

I remember Hubspot needed a separate request for each custom field, and Marketo requires a personalization package add-on which I've never worked with because it's so expensive.

**Comment by chrisblakley** [comment]
For Hubspot, I'd like to integrate the [Form API](https://developers.hubspot.com/docs/methods/forms/submit_form) into the companion app since it requires a paid Marketing account (since you have to create a form in Hubspot in order to send data to it from third-party).

**Comment by chrisblakley** [comment]
I'm going to close this now as we have CRM integration. For additional integration we can make individual issues.
