### ISSUE TITLE
Shortcodes are autop and automatically adds br

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1191]
I am using Easy Digital Downloads (edd) with Nebula

In some edd shortcodes nebula is autop the shortcode content, I tried to remove the code at functions/nebula_shortcodes.php lines 530, 531 and 532 and everything works correctly

Also, in edd checkout form, nebula adds `br` tags after `span` and `label` tags

**Comment by rubengc** [comment]
After some tests, removing same lines from nebula_shortcodes.php (530, 531 and 532) fixes the problem of extra `br` at edd checkout form

**Comment by chrisblakley** [comment]
Interesting find- thanks for bringing it up. I'll look into altering that functionality- I had it in there because the `wpautop` was adding `<p>` tags within other shortcodes so that moves it to after the shortcodes.

**Comment by rubengc** [comment]
Yes, I found this as solution googling, but at least, with EDD active, this does not works (I do not know why this happens)

**Comment by rubengc** [comment]
Removing nebula_shortcodes.php 530, 531 and 532 lines solves the problem with my plugin and nebula shortcodes works correctly too

If you need to make some extra test let me know, i will PR this changes to close this

**Comment by chrisblakley** [comment]
I'd probably be fine with commenting those lines out for now- I can't remember specifically, but I added them because of some weirdness with Nebula shortcodes a while back so in the future I may re-enable them unless I can find more specifically what my older issue was.

**Comment by rubengc** [comment]
Has PR
