### ISSUE TITLE
Nebula option comments functionality

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1192]
The nebula option comments (enable or disable) forces the entire site to allow/disallow comments

If you are disabling comments this functions work well but enabling this will allow user to comment on each page (included If post/page has settings disabled)

I think enable comments should keep wordpress default workflow

I open this issue to justify next PR I will send

**Comment by chrisblakley** [comment]
Interesting find- I typically use Disqus for commenting, but will look forward seeing what you find from your PR. Thanks!

**Comment by rubengc** [comment]
Oh is easy, on nebula_functions.php you are forcing to comment/ping with this lines

Removing them problem gets fixed

```php
        //Open comments on the front-end
	add_filter('comments_open', 'enable_comments_status', 20, 2);
	add_filter('pings_open', 'enable_comments_status', 20, 2);
	function enable_comments_status(){
		return true;
	}
```

**Comment by rubengc** [comment]
I am thinking on this, do you want to keep enable functionally and add new option "Default" pointing in description this?

Default -> Wordpress default
Enable -> Comments enabled to all
Disable -> Comments disabled to all

**Comment by chrisblakley** [comment]
"Default" on Nebula is the sort of "typical default" for the type of client-based brochure style website, so in the example you provided the ideal would be:

Default -> Comments disabled to all
Enable -> WordPress default (w/ Disqus override)
Disable -> Comments disabled to all

**Comment by rubengc** [comment]
No no, I refer to a new setting to keep wordpress default 
the comments options select with 4 choices:
Default: Disable
WP Default
Enable (to all)
Disable (to all)

I added a PR that fixes comments option when enabled keeping wordpress default

**Comment by chrisblakley** [comment]
Thanks for the PR- I'll merge that soon.

Regarding the Nebula Options- those are technically just boolean settings. The "default" is more of a hint for the user if is not changed, the default will be X (So it doesn't have any different functionality).

In this case, the commenting option (as far as Nebula goes) should either be completely disabled, or allow WordPress to handle it (enabled). So your pull request is perfect and will fix the issue without needing to expand the Nebula Option.

**Comment by rubengc** [comment]
But Do not you think is a bit dangerous disable comments by default?

**Comment by chrisblakley** [comment]
I would agree if Nebula was used for mostly blogging websites, but since it's being used primarily for brochure-style websites I have it set to disable.

My personal opinion is that I see more danger in an admin forgetting to disable the comments and have spam issues (or PR issues if the comments are visible) when not intended- which is why I'm glad you caught that bug.

**Comment by rubengc** [comment]
Watching this on that way, you're right!

and I am glad to help ^^
