### ISSUE TITLE
Rand and mt_rand functions warnings on windows

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1198]
On my server everything works good

But on windows (64-bit) rand and mt_rand functions shows "expects parameter 2 to be integer, float given"

To avoid this only is needle change second parameter (99999... infinite) to `mt_getrandmax()`

**Comment by chrisblakley** [comment]
I updated this in `metadata.php` and `nebula_admin.php`. Looks like the other locations have an actual ceiling integer. Will push eventually.
