### ISSUE TITLE
See if we can jam the JS API into WordPress oEmbeds.

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1200]
See if we can get the WP oEmbed for Youtube to enable the JS API and therefore Nebula event tracking.

**Comment by rubengc** [comment]
What do you want exactly?

**Comment by chrisblakley** [comment]
Looking into something like this:

https://core.trac.wordpress.org/ticket/29534
```php
add_filter('oembed_result', 'enable_yt_jsapi');
function enable_yt_jsapi($html, $url, $args) {
	if (strstr($html, 'youtube.com/embed/')) {
		$html = str_replace('?feature=oembed', '?feature=oembed&enablejsapi=1', $html);
	}
	return $html;
}
```

Specifically, the `&enablejsapi=1` part so that Youtube oEmbeds will be captured when Nebula looks for Youtube videos to track interaction.

**Comment by chrisblakley** [comment]
Ok, all set. I piggybacked off the `nebula_embed_oembed_html` filter that already existed in `nebula_functions.php` so it now enabled the JS API for Youtube videos. Just tested it and now Nebula can see them, listen for events, and control them.
