### ISSUE TITLE
Customizer improvements

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1201]
I think new customizer needs a small improvements to get it completely finished

1 - Logo, title and description in header with checkboxes to hide them
This will allow set only logo, logo + title or logo + title + description (to hide logo, simply not set it)

2 - static front page options to toggle hero slider visibility and options to set h1 and h2 content (instead of site title and description)

If you are ok with this I can PR with this options (including the text color option you mentioned)

**Comment by chrisblakley** [comment]
Yeah I'd be cool with those- feel free to make a PR and I'll merge it.

**Comment by rubengc** [comment]
Nice, I will focus on finish the customizer to full work this weekend on implementing register stylesheets/templates and finish EDD integration and build the nebula plugin integration boilerplate

A lot of todos to solve 😄

**Comment by rubengc** [comment]
I see you keep search input in footer so I will update customizer with this option

**Comment by chrisblakley** [comment]
I did finally get to these updates and they are implemented now. Will be doing more with the Customizer soon.
