### ISSUE TITLE
[Structure] Page templates should be on "page-templates" directory

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1210]
Wordpress search in this folder to load page templates too

So as improvement to nebula file structure could be move this file into page-templates directory

**Comment by chrisblakley** [comment]
I would be cool with this. My thought would be custom templates can be moved to the templates directory, but I'd like to keep core templates (archive.php, category.php, page.php, single.php, etc.) in the root directory.

I'm thinking we keep the directory name simple and just call it `templates`.

**Comment by chrisblakley** [comment]
Weird, I used to run all documentation example templates in a directory called "examples" and WordPress found them fine. I just did a test and it successfully found a template in a directory called `testing`.

I'd really like to simplify the directory name, so I'm going to poke around to see what other themes are doing- just seems strange to require a directory with such a long name.

**Comment by rubengc** [comment]
This is only to organize a bit more the project but if you are ok with current page templates we could keep current structure (there is only two page templates, so is not so much important at this moment)

I will update template engine with that

**Comment by rubengc** [comment]
Forgive that, I was bad documented about this
