### ISSUE TITLE
ScrollTo should not work on bootstrap tabs

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1212]
Currently [bootstrap nav tabs](http://v4-alpha.getbootstrap.com/components/navs/#using-data-attributes) are imposible to use, every time you click a tab you get scrolled to the tab-pane element

I suppose nebula has a js function searching for internal anchors and scrolling to the id given, so a conditional selector matching bootstrap class should solve the problem

**Comment by chrisblakley** [comment]
You are correct. I'll troubleshoot and update.

**Comment by chrisblakley** [comment]
All set- updated the disallowed parent selectors. I was vague and disabled it for anything with a `data-toggle` attribute (and a couple others).

As a note, using the class `no-scroll` on either the anchor or any of it's parents will disable the scrollto functionality too. I don't want that to be required to disable it when it's obviously not suppose to trigger, so if you (or anyone else) finds other common ones please report them.
