### ISSUE TITLE
Revisit the theme updater when there is an incompatible remote version

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1214]
Right now it does a ton of extra steps to force disable automated remote updates. It's so locked down that even after manually updating, it is tough to get it to resume automated updates.

Maybe instead of disabling the function and doing several other steps it just simply disables function. It could also set another function to show helper text. If this is used, the remote version checker will run regardless of setting.

**Comment by rubengc** [comment]
I do not revise this function in deep, but my desired workflow is:

- Try to update
- If fails send to me an email with error
- Disable auto update
- Enable a notification with two options: Problem fixed, try again, Dimiss notice

**Comment by chrisblakley** [comment]
This function is ultimately manually triggered by the admin, so there isn't a fail state. I implemented this to easily update projects that are live to the latest version of Nebula by piggybacking on the WordPress theme updater. Sometimes (like with the upcoming OOP build) I'll declare the version not backwards compatible juuust in case it could possibly break a client's live website. When I do this, I have the older themes automatically prevent future one-click theme updates. But I do this a little too hardcore right now because I'm a worry-wart.

I'll look into this some more eventually.

**Comment by chrisblakley** [comment]
This could be a really stupid idea, but just to put the idea out there. I could set up something on the Github side that gets mis-matched (like a string) when an incompatible version is committed. Then, in order to update, a dev would need to update the string to match Github to allow the connection to work again.

The thing I like about this is that since updating from legacy back to active requires a developer anyway, so this is a check that they know how to handle it. It would also 100% prevent it from being accidentally updated. Even more, the update would not even show up until the string is updated.

What I don't like it is that it just doesn't seem like a professional way to go about it. It could also potentially add one more remote get on the WP Admin.
