### ISSUE TITLE
Would a pre-launch check tool be useful to prevent common issues?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1215]
Maybe a WordPress admin page for developers that checks for common issues (Basically just a search through theme files for strings). This would be intended to be used prior to launching a website.

It could check for:
- console.log
- console.debug
- @todo comments
- Missing Google Analytics ID
- Search engine visibility
- var_dump

What else could be caught?

This might be better as a plugin... or maybe not worth pursuing.

**Comment by rubengc** [comment]
I like this idea

I want to recommend improvements to todo manager allowing to catch `//todo` `// todo` setting as category the file name and priority 0

**Comment by chrisblakley** [comment]
I'm all for enhancing the todo manager- so feel free to play around with the detection. There are some known bugs that I think I've made issues for.

Regarding the priority 0, that is done on purpose- priority 0 is hidden from the todo manager purposefully. This is so Nebula todos are not interfering with project theme development todos (and in case a dev doesn't want a todo to appear in the list for whatever reason).

On my dev server, I added an override to show all priority 0 (hidden) todos, and I've thought about adding a toggle for the user to see them, but I decided against it.

**Comment by rubengc** [comment]
A note for todo manager and pre launch check tool

Will be useful get differents dashboard metaboxes for each location (one with nebula, another one to child theme and other coming from nebula registered plugins)

**Comment by chrisblakley** [comment]
Here's another cool idea for a pre-launch visual tool:

```css
img:not([alt]),
img[alt=""] {
 border: 2px dashed red;
}
```

**Comment by chrisblakley** [comment]
This is now implemented in the companion plugin as "Audit Mode" which enhances the normal Nebula warning array and also adds a bunch of extra DOM checks.
