### ISSUE TITLE
Take a look to this plugin

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1218]
[Wordpress Helpers](https://es.wordpress.org/plugins/wp-helpers/) has some functions that could be really useful to implement on nebula or compare with our current ones

**Comment by rubengc** [comment]
I revise the plugin code

Basically is a visual options changer of [Piklist](https://wordpress.org/plugins/piklist/) :/

So to review how it implements this function we need to revise piklist code

**Comment by chrisblakley** [comment]
Nebula actually does a lot of this functionality- if there are any specifics that it lacks I'd recommend making feature requests for it. I tend to avoid plugins unless absolutely essential, and even then Nebula must be able to work 100% independently of plugins.

**Comment by rubengc** [comment]
I mean to check their code to see If they archieve some of current nebula functionalities in a better way or If you want to add some of their functionalities to nebula

**Comment by chrisblakley** [comment]
Ah yeah, in that case I'm open to ideas- I'll look through more in-depth tonight to see if there is anything enticing.

**Comment by rubengc** [comment]
Nice! Remember to check [Piklist](https://wordpress.org/plugins/piklist/)  

WordPress helper is only an UI to change Piklist options values

**Comment by rubengc** [comment]
What do you think about integrate private site functionallity?

This means require login to guest visitors
