### ISSUE TITLE
If Contact Form DB plugin does not return to WP Plugins Repo, find a new one.

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1222]
No longer exists: https://wordpress.org/plugins/contact-form-7-to-database-extension/

Need to find an alternative that stores Contact Form 7 submissions to the database.

Looked into Flamingo, but not in love with it.

**Comment by chrisblakley** [comment]
https://wordpress.org/support/topic/is-cfdb-gone/

Looks like it was moved to Github. If it doesn't get re-listed into the WP Plugin Repository, I'll still want to find a new one so that we can bundle it with Nebula and get automated updates.

**Comment by rubengc** [comment]
There is a lot of plugins doing the same so probably is better to switch to another one with best support

**Comment by chrisblakley** [comment]
Here's one with good reviews: https://wordpress.org/plugins/save-contact-form-7/

**Comment by chrisblakley** [comment]
Trying out Save CF7 plugin.
