### ISSUE TITLE
Consider better organizing of theme file structure.

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1224]
I see a lot of pro themes has their client side resources located in assets directory and each one in their respectives folders and one called lib to store all external resources

We could keep this folder structure too (also on nebula integrations)

Of course we need to update sass compiler too

**Comment by chrisblakley** [comment]
We can maybe look into this eventually, but I'm not sure I'm ready to make a change like this quite yet.

**Comment by chrisblakley** [comment]
For reference, here's how the WordPress core themes do it. Notably, the twentyseventeen theme is the first to use an `/assets/` directory.

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes?order=name

Potential Nebula structure could be something like:
- Nebula-master
  - assets
    - css
    - scss
    - img
    - js
  - page-templates
    - Move `tpl-*.php` files here (and then remove `tpl-` prefix)
  - inc
    - libs (or vendor?)
    - data
  - functions

This would definitely require a lot of updates to code that references file structure (as well as in Nebula-child). If we are going to adjust the structure, I would probably recommend changing directory names to for more consistency (ex: `images` to `img`).

**Comment by rubengc** [comment]
I mark this as next before merge nebula OOP PR

I will update sass compiler for this new structure, and also I will update plugin integration folders (for boilerplate and current EDD integration)

**Comment by chrisblakley** [comment]
I'm going to jump on this tonight and see how much it breaks other functions.

**Comment by chrisblakley** [comment]
This was easier than expected, so I'll make the next push with the new organization.
