### ISSUE TITLE
Add "Last IP" column to the Users list?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1237]
Consider adding a column to the User listing to show last IP address.

**Comment by rubengc** [comment]
Also consider add a registered date column

**Comment by chrisblakley** [comment]
If the IP address is in the Notable IP list, add the notable name in parenthesis (maybe in `<small>` tags) after the IP.

**Comment by chrisblakley** [comment]
Added Last IP w/ Notable POI and a column for registered date.
