### ISSUE TITLE
Improve sidebars

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1238]
We have 2 sidebar areas separated by a sidebar menu

WordPress has a custom menu widget where you can locate any menu(s) at any sidebar and at any position

So we could consider remove secondary sidebar area and keep only one

**Comment by rubengc** [comment]
Let me know If you are ok with this change, there are a few lines to edit so it is a easy change

**Comment by chrisblakley** [comment]
Yeah I'd say go for it.

**Comment by chrisblakley** [comment]
I took care of this.
