### ISSUE TITLE
Bootstrap modal is broken

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1239]
Bootstrap modals still not working, there is the list of things that happens:

1 - modal overlay is over the modal (making it unclickable), problem comes from z-index CSS rule
2 - modal is positioned at top (modal title is out of screen)
3 - modal content is zoomed and blurred (idk what happens here)

**Comment by chrisblakley** [comment]
I believe this was caused by a conflicting style with Mmenu. One of our devs found the solution and I've included the fix with the last push, so this should be fixed now.
