### ISSUE TITLE
Separate grep for .scss files from Sass processing function

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1240]
Create a new function that finds .scss files and adds them to an array of `array(path, destination)`. 

Use `apply_filter()` so that plugins can also add .scss files to be processed.

Then in the Sass processor, just loop through all prepped Sass files.

This would be a solution to the code-debt of having duplicate functions for Sass processing.

**Comment by rubengc** [comment]
For nebula integrations I would keep current behavior (registering the plugin, will process sass files automatically If plugin keeps our folder structure)

Also Nebula_Sass class should search in assets/scss folder instead of stylesheets/scss

Another task It should do is minify resources if SCRIPT_DEBUG is not defined or is set to false, also, should sass compiler store them into .min.css file instead of a common .css file?

About imports, is possible to make It work with .scss files not in partials folder? I test It but it does not work (sass compiler ignore this imports)

On get this I will update nebula boilerplate and nebula EDD integration with latest changes

**Comment by rubengc** [comment]
A note, check scandir function in Nebula_Template_Engine class

Probably scandir function should come inside utilities or inside a filesystem class (because todo manager also scan dirs)

**Comment by chrisblakley** [comment]
Ok, I've modified how Nebula SCSS works- it's much more flexible now (and we may not even need to register plugins with Nebula at all).

Nebula now uses an array of Sass file locations and finds .scss files within that location. It can have custom partials locations, too. It uses a filter I named `nebula_scss_locations` so this array can be added to.

Here's what the array looks like:
```php
array(
	'parent' => array(
		'directory' => get_template_directory(),
		'uri' => get_template_directory_uri(),
		'partials' => get_template_directory() . '/stylesheets/scss/partials/'
	)
)
```

To add to this array within a plugin (or anywhere else), use the filter like this:
```php
add_filter('nebula_scss_locations', 'my_plugin_scss_files');
function my_plugin_scss_files($scss_locations){
    $scss_locations['my_plugin'] = array(
		'directory' => plugin_dir_path(__FILE__),
		'uri' => plugin_dir_url(__FILE__),
		'partials' => plugin_dir_path(__FILE__) . '/scss/partials/' //Change this to wherever your partials files are.
	);
    return $scss_locations;
}
```

Other notes:
- File minification is controlled by a Nebula option
  - Can not use `*.min.css` without also changing the `wp_register_style()` path in functions.php. To me, that's just another moving part vulnerable to breaking.
- I could add another key to the array for additional import files. If you could write-up a use-case to help me understand it better I can try to work that in.
- This update will be easy to update when we switch to an /assets directory.

**Comment by rubengc** [comment]
What do you think about change `nebula_register_plugin( $name, $path )` to `nebula_register_plugin( $name, $args )`?

Where $args has the plugin path, plugin templates and plugin scss locations

This let us add more args to future functionalities

**Comment by chrisblakley** [comment]
Can you remind me what we need that function for? The only thing that doesn't account elsewhere (now) is the plugin templates directory. Ideally we'd find a way to not need to use a register function at all- maybe in the templating engine we can throw in an `apply_filter()` so that the plugins can add their template directory right from within the plugin itself (and not inside of Nebula master).

**Comment by rubengc** [comment]
Basically is an utility to register templates and scss files easily in nebula

I think giving an easy way to devs to create an integration in nebula will be more attractive to develop under the nebula enviroment

Check this:
https://github.com/rubengc/nebula-edd/blob/master/nebula-edd.php#L170
