### ISSUE TITLE
Action hooks in nebula options

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1244]
Basically I am setting up GA ecommerce support using EDD so we could change `cd_woocart` and `cd_woocustomer` options to `cd_cart` and `cd_customer` and use same options for ecommerce dimensions

or, remove this options and only enable them when Woo is enabled and add a filter at end of "Custom Dimensions" form to allow plugins add form inputs, with this I can add  `cd_eddcart` and `cd_eddcustomer` and if anyone wants to use both plugins or another plugin that allows sell anything like LearnPress (that allows sell courses)  we can get them separated by their plugins

**Comment by chrisblakley** [comment]
I'll take care of this this weekend, good idea.

**Comment by rubengc** [comment]
Thinking about this, It should be an action hook where integrations adds their custom options so I will update issue title

Check the PR about nebula OOP and I could add this when I rewrite options inputs

**Comment by chrisblakley** [comment]
Yeah I like the idea of additional options. For now, I'm just going to change those two cd_ names, but ultimately we can add some hooks for entirely custom options. I'll either add a "Custom" tab to Nebula Options, or allow for hooking into a sub-page in the WP admin.

**Comment by chrisblakley** [comment]
I'm going to also tag on here to look around for more places to add `do_action()` hooks in Nebula too.

**Comment by chrisblakley** [comment]
Here are the actions I'll be adding to the Options page in May:
 - `nebula_options_interface_additional_tabs`
 - `nebula_options_interface_preset_filters`
 - `nebula_options_interface_metadata`
 - `nebula_options_interface_functions`
 - `nebula_options_interface_analytics`
 - `nebula_options_interface_apis`
 - `nebula_options_interface_administration`
 - `nebula_options_interface_additional_panes`
 - `nebula_options_interface_diagnostic`
