### ISSUE TITLE
Look into catching and reporting fatal errors with PHP7

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1247]
Look into tracking fatal PHP errors in Google Analytics (and/or NVDB). Will need to check for PHP7 first (or may even need to wait until PHP7 is the norm).

**Comment by rubengc** [comment]
I am working completely with PHP7, so i will enable this functions to see if everything works

**Comment by chrisblakley** [comment]
We'll just want to wrap it in a PHP version number check so that it doesn't _cause_ a fatal error in 5.6 (or lower).
