### ISSUE TITLE
Look into Github Updater for theme updates

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1265]
Look into this plugin for theme updates: https://github.com/afragen/github-updater

This would replace the `theme-update-checker.php` vendor file.

Not sure how I'd bundle it with Nebula... Maybe it's just another required plugin with TGMPA? Can that even support plugins outside of WordPress.org?

This would be a good way to enable/disable automated theme updates. I'll have to try it first to see if it's even an option.

**Comment by rubengc** [comment]
I tested this pllugin long time ago, I dascard it at this moment because it caused me some performance problems while is checking for updates

**Comment by chrisblakley** [comment]
Cool, thanks for the info. I do really like the method I'm using now, so it'll take quite a bit to convince me to go with something else.

**Comment by rubengc** [comment]
We can create a trait that handles github updates that could be useful for #1275

**Comment by chrisblakley** [comment]
Closing this one as I've decided to keep the theme updater as is (at least for now).
