### ISSUE TITLE
Should index.php be empty? What are other themes doing?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1266]
I thought I remember seeing other themes with empty index.php files.

When the setting "Latest Posts" is selected for front-page, what file is controlling that (if not index.php)?

**Comment by rubengc** [comment]
empty index.php is to prevent list files, I do not follow this practice but I will read why some themes/plugins have this

**Comment by chrisblakley** [comment]
Yeah, I do the same and back it up with `.htaccess`, so I'm more interested in seeing how other themes pull in the "Latest Posts" feed.

**Comment by rubengc** [comment]
Are you talking about home.php? WordPress team refence this in their theme development documentation:

https://codex.wordpress.org/Theme_Development
