### ISSUE TITLE
No way to reset the Customizer

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1268]
This is a continuation of our discussion in this [Pull Request](https://github.com/chrisblakley/Nebula/pull/1205#issuecomment-285742973).

I'm running into issues again with the Customizer. I like the idea of it, but I keep running into problems. Is there no way to reset the colors?

If I set a color using the Customizer, everything updates to that color, which is great. But then if (for whatever reason) I want to reset the Customizer so that my Sass colors are used again, I'll click "Default" in the Customizer and re-save, but now it still pulls the Customizer color- just the default one instead of falling back to the Sass color.

It seems that once the Customizer is used once, it can't not be used thereafter. Like, get_theme_mod() will never fall back to the 2nd parameter...

I see plugins that claim to truly be able to reset the Customizer, but I don't want to install a plugin just for the purpose.

Any thoughts on this? Maybe I'm doing something wrong (as I'm still new to the Customizer)?

**Comment by rubengc** [comment]
Note: Deactivating all plugins and reactivating them customizer works!

thanks to @SDavisMedia he helps to find the bug

**Comment by chrisblakley** [comment]
I'm still having difficulty with the ```get_theme_mod('nebula_primary_color', nebula()->sass_color('primary'))``` function. This time I have the colors set using the Customizer, but now it isn't pulling it through the Sass at all. If I don't use that function, it works fine by pulling the color from the child theme partials file.

What would you think about a Nebula option that enables/disables the Customizer overall?

Again, I'm still new to using the Customizer, so these could be growing pains.

**Comment by chrisblakley** [comment]
I might have solved this by defaulting some of the settings to `null`.
