### ISSUE TITLE
Look into The SEO Framework plugin as a possible Yoast replacement

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1269]
I'm always seeing lots of Yoast hate in the community, but never found an acceptable alternative. [The SEO Framework](https://wordpress.org/plugins/autodescription/) seems like the first contender. Look into bundling it with Nebula instead of Yoast.

**Comment by rubengc** [comment]
Looks nice, I will test this plugin as soon as posible

**Comment by rubengc** [comment]
Oh, just a little note, I replaced yoast from some installs to this one

SEO score is similar (or probably I got better visibility) and the great improvement comes from page load times at post edit screen

**Comment by chrisblakley** [comment]
Our clients have been using the focus keyword tool in Yoast (and I do like their keyword tools). I haven't completely ruled out replacing it, but we're going to stick with it for the foreseeable future. Will re-open if needed in the future.
