### ISSUE TITLE
Redesign the Nebula Options admin page

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1277]
This will be for discussion of redesigning the Nebula Options page.

I want it to look nicer, but also accommodate more hooks and general better usability. I'd like the "help" text to be visible (or at least the gist) by default and maybe have a button to show more in-depth instructions when necessary.

**Comment by chrisblakley** [comment]
Here are some other theme options pages that look nice.

This one has vertical tabs instead of horizontal which would be good to allow more and more Advanced Plugin hooks:
![f1](https://cloud.githubusercontent.com/assets/6349678/23926692/ffaebf5a-08eb-11e7-8c80-d460d89a3173.png)

**Comment by rubengc** [comment]
+1 for vertical tabs

**Comment by rubengc** [comment]
Finally what you decide about this? Keep nebula plain settings page or use an external library?

**Comment by chrisblakley** [comment]
I haven't sketched out any layouts yet, but I'd like to just code the page within Nebula (without using an external options library).

**Comment by rubengc** [comment]
Nice so I will continue updating the options PR with hooks at each section, are you ok with this?

**Comment by chrisblakley** [comment]
Yep, we can definitely get the hooks in there in the meantime.

**Comment by chrisblakley** [comment]
Adding a note for when I design this- it'd be nice to have a filter input field to find options by keyword. I didn't remember where I put the Modernizr option and a real-time search filter would have helped find it under "Browser/Device Detection".

**Comment by chrisblakley** [comment]
Here's a start. I'll update this image as I make changes to it. I'm thinking I'll pull in Bootstrap for just this page so I can utilize the responsive grid- so on wider screens, more options can be shown in the right columns.

When filtering, all tabs will be opened to show all relevant options.

![nebula-options](https://cloud.githubusercontent.com/assets/6349678/25213223/208714a6-255d-11e7-872c-27f59db6ba78.png)

Haven't decided yet how the boolean toggles will work.

**Comment by chrisblakley** [comment]
I'm planning on adding a new `/Options` directory to the `/libs` which will contain `Interface.php`. This will be in addition to keeping `Options.php` (where the interface will be called from).

**Comment by chrisblakley** [comment]
Might need to alter how the Enable/Disable buttons look.

Here are some interesting ideas:
 - https://codepen.io/mburnette/pen/LxNxNg
 - https://codepen.io/mallendeo/pen/eLIiG

**Comment by chrisblakley** [comment]
Preview of the new options interface: https://gearside.com/nebula/wp-content/themes/Nebula-master/libs/Options/Interface.php

Not connected to anything, and it may break while I'm working on it.

**Comment by chrisblakley** [comment]
Once this is implemented, look into updating `nebula()->option()` to better work with the boolean checkboxes (since it isn't going to be an 'enabled' or 'disabled' string value anymore).
