### ISSUE TITLE
Would a design reference Dashboard metabox be useful?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1278]
Would it be useful to have a "Design Reference" metabox? This metabox would include data such as:
- Primary Color (Hex and RGB Values)
- Secondary Color
- Background Color
- Text Color
- Font Stack

...any other info? Maybe even a link to the design itself?

@patphg

**Comment by rubengc** [comment]
Not sure about this metabox, the theme colors are visible in frontend and customizer
