### ISSUE TITLE
Export DB to have stable version releases on PHG's server

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1281]
Use WP-Cron to export the database so it can be mirrored on PHG to establish our stable version releases.

@jefphg We can log our details here as needed.

**Comment by chrisblakley** [comment]
Might be able to even use this plugin to send the data via FTP:
https://en-ca.wordpress.org/plugins/all-in-one-wp-migration/

**Comment by chrisblakley** [comment]
The All-In-One Migration plugin FTP add-on is $99. Plus I'd have to manually trigger the export (I think).

I think it'd just be easier to write a cron to automate the export the db myself.

**Comment by chrisblakley** [comment]
How will we update the theme on the PHG server without being able to log into the wp admin?

I have 2 ideas:

1. Write a plugin that automates it somehow
2. Do a find/replace on the DB file when importing to change the "site_url" option (and maybe others) to https://nebula.pinckneyhugo.com

**Comment by chrisblakley** [comment]
This in wp-config.php did the trick:
```php
define('WP_HOME', 'https://nebula.pinckneyhugo.com');
define('WP_SITEURL', 'https://nebula.pinckneyhugo.com');
```

**Comment by chrisblakley** [comment]
Only things that aren't pulling over automatically:
- Logo
  - The image is not appearing and falling back to the site title "Nebula". I didn't think I set that manually somehow on the documentation site, but maybe I did...?
- Menu display locations
  - The menus are fine, but the display location checkboxes are all unchecked for some reason.

**Comment by chrisblakley** [comment]
The logo appears to have been set in the Customizer, so maybe it's just missing the image file itself?

I wonder if we should just use the plugin I created on the PHG server to manually insert the logo image itself.

**Comment by chrisblakley** [comment]
Some additional notes:

- On DB import, it appears the plugins get deactivated for some reason (may not happen every time?)
- Disable search indexing on the PHG server in our plugin
- Figure out how to migrate the service worker. May need to copy it over and then cURL a pageivew with `?sass=true` so the sw.js file doesn't retain gearside.com

**Comment by jefcollier** [comment]
cURLing on our PHG server at 06:00:
`./get_nebula_db`

**Comment by chrisblakley** [comment]
Inside the plugin I think we'll need two more things:
- [ ] Modify the Nebula option for GA Tracking ID (to keep it separate from Gearside GA)
- [ ] Modify the WordPress core search indexing option to disable search visibility

**Comment by chrisblakley** [comment]
WP login logo disappears too

**Comment by chrisblakley** [comment]
Ok, so the two things we're up against now are:

- [ ] DB export on the Gearside server is not allowing (or at least as far as I can tell) the `mysqldump` command. PHP alternatives aren't exporting in a way that we can simply import via cron command on the PHG server

- [ ] Menu locations are still not being checked after an import happens. This must be tied to the theme somehow (...but the theme is the exact same...)?

**Comment by chrisblakley** [comment]
This might be able to help:
https://wp-cli.org/

```
wp search-replace 'https://gearside.com/nebula' 'https://nebula.pinckneyhugo.com' --precise --recurse-objects --all-tables
```

**Comment by chrisblakley** [comment]
I'd also like to append a timestamp (via the mu plugin) somewhere in the DOM of when the last DB sync occurred.

**Comment by chrisblakley** [comment]
Noted this in #1957 but with Github Actions, it could be even easier to trigger this whenever a Nebula commit is made: https://github.com/appleboy/ssh-action

**Comment by jefcollier** [comment]
@Team: Chris & I had a script on the PHG server that attempts to fix some of this, but we can't get it to work automagically.  Some details on how to dive into this:
____________________

If you're in the office, you'll need to hosts file this because our network is fucky:
`sudo vim /etc/hosts` and add this line:
`72.52.253.57 nebula.pinckneyhugo.com`

Next, you can shell into nebulaphg and look here:
`/home/nebulaphg/DB/`
_(This is above public_html, so plz don't ask me why you can't just FTP in.)_

Within that location is this script which attempts to run nightly around 0100 (via crontab):
`get_nebula_db.sh`

The contents are:
```bash
#!/bin/bash
HOST='ftp.gearside.com'
USER='nebuladb@gearside.com'
PASSWD='{!!!REDACTED!!!}'

ftp -n -v $HOST << EOT
binary
user $USER $PASSWD
prompt
ls -lah
get db.sql
get sw.js
get nebula-docs.zip
bye
EOT

# Database credentials
db_user="nebulaph_wp"
db_pass="ugo572$PHG"
db_host="localhost"
db_name="nebulaph_wp"
db_path="/home/nebulaphg/DB"
date=$(date +"%d-%b-%Y")
timestamp=$(date +"%F %T")

echo 'Exporting a backup, just in case...'
# Backup DB
mysqldump nebulaph_wp > nebulaph_wp_bak.sql
#mysqldump --user=$db_user --password=$db_pass --host=$db_host $db_name > $db_path/$db_name-$date.sql


echo 'Replacing strings to allow this export to function within our environment...'
#Replace DB Variables
sed -i -e "s/utf8mb4/utf8/g" db.sql;
sed -i -e "s/utf8_unicode_520_ci/utf8_unicode_ci/g" db.sql;

echo 'Dropping all tables...'
# Drop all the tables
mysql -Nse 'show tables' nebulaph_wp | while read table; do mysql -e "SET FOREIGN_KEY_CHECKS = 0; DROP table $table" nebulaph_wp; done

echo 'Importing fresh DB...'
#Import new DB
mysql nebulaph_wp < db.sql

echo 'Replacing URLs...'
wp search-replace 'https://gearside.com/nebula' 'https://nebula.pinckneyhugo.com' --precise --recurse-objects --all-tables --path='../public_html/'

echo 'Moving files...'
mv sw.js ../public_html/
unzip -o nebula-docs.zip -d ../public_html/wp-content/plugins/
chown -R nebulaphg.nebulaphg ../public_html/*

echo 'Writing DB Timestamp'
echo "{\"last\":\"$timestamp\"}" > '../public_html/wp-content/mu-plugins/phg-nebula/data/db.json'
```

Finally, if you run this manually as root, it is fine (you can see I chown it after the fact).  But when attempting to run this automatically via cron, something breaks.  We suspect it's permissions related.

**Comment by jefcollier** [comment]
@Team: Chris & I had a script on the PHG server that attempts to fix some of this, but we can't get it to work automagically.  Some details on how to dive into this:
____________________

If you're in the office, you'll need to hosts file this because our network is fucky:
`sudo vim /etc/hosts` and add this line:
`72.52.253.57 nebula.pinckneyhugo.com`

Next, you can shell into nebulaphg and look here:
`/home/nebulaphg/DB/`
_(This is above public_html, so plz don't ask me why you can't just FTP in.)_

Within that location is this script which attempts to run nightly around 0100 (via crontab):
`get_nebula_db.sh`

The contents are:
```bash
#!/bin/bash
HOST='ftp.gearside.com'
USER='nebuladb@gearside.com'
PASSWD='{!!!REDACTED!!!}'

ftp -n -v $HOST << EOT
binary
user $USER $PASSWD
prompt
ls -lah
get db.sql
get sw.js
get nebula-docs.zip
bye
EOT

# Database credentials
db_user="nebulaph_wp"
db_pass="{!!!REDACTED!!!}"
db_host="localhost"
db_name="nebulaph_wp"
db_path="/home/nebulaphg/DB"
date=$(date +"%d-%b-%Y")
timestamp=$(date +"%F %T")

echo 'Exporting a backup, just in case...'
# Backup DB
mysqldump nebulaph_wp > nebulaph_wp_bak.sql
#mysqldump --user=$db_user --password=$db_pass --host=$db_host $db_name > $db_path/$db_name-$date.sql


echo 'Replacing strings to allow this export to function within our environment...'
#Replace DB Variables
sed -i -e "s/utf8mb4/utf8/g" db.sql;
sed -i -e "s/utf8_unicode_520_ci/utf8_unicode_ci/g" db.sql;

echo 'Dropping all tables...'
# Drop all the tables
mysql -Nse 'show tables' nebulaph_wp | while read table; do mysql -e "SET FOREIGN_KEY_CHECKS = 0; DROP table $table" nebulaph_wp; done

echo 'Importing fresh DB...'
#Import new DB
mysql nebulaph_wp < db.sql

echo 'Replacing URLs...'
wp search-replace 'https://gearside.com/nebula' 'https://nebula.pinckneyhugo.com' --precise --recurse-objects --all-tables --path='../public_html/'

echo 'Moving files...'
mv sw.js ../public_html/
unzip -o nebula-docs.zip -d ../public_html/wp-content/plugins/
chown -R nebulaphg.nebulaphg ../public_html/*

echo 'Writing DB Timestamp'
echo "{\"last\":\"$timestamp\"}" > '../public_html/wp-content/mu-plugins/phg-nebula/data/db.json'
```

Finally, if you run this manually as root, it is fine (you can see I chown it after the fact).  But when attempting to run this automatically via cron, something breaks.  We suspect it's permissions related.

**Comment by chrisblakley** [comment]
Quick note that Gearside Nebula was migrated to AWS, so any FTP or connection accounts related to this were **not** included. If we want to continue this pursuit I'll need to re-make them. Also the IP has changed.

**Comment by chrisblakley** [comment]
Something like this plugin could be interesting and maybe it would make this easier: https://wordpress.org/plugins/wp-staging/

@jefcollier

**Comment by chrisblakley** [comment]
Closing for now and we can always revisit and reopen this issue.
