### ISSUE TITLE
Can't change/remove header or logo (Improve Customizer Support)

### ISSUE THREAD

**Issue by JulianKingman** [chrisblakley/Nebula#1372]
Hi @chrisblakley,

Your theme is beautiful and has some pretty cool features, but there are a few basic things I can't figure out:
- How do I remove the header on the homepage?
- How do I change the logo?
- How do I remove the search bar?

I have options to change these in the `customize` menu, but they don't appear to actually have an effect (pictured below)

<img width="1658" alt="screen shot 2017-06-06 at 6 38 21 pm" src="https://user-images.githubusercontent.com/1566400/26855126-59da2068-4ae7-11e7-83be-8018e35a4dbc.png">

PS, I lived in Syracuse for a year and worked out of the tech garden and coworks. Small world.

**Comment by chrisblakley** [comment]
Thanks for the post! We actually just started implementing Customizer support a few months ago, so there very well could be some bugs still in there.

Originally (and still the main purpose), Nebula provided a quick way for developers to dive into the templates and overhaul the pieces into what they wanted, and recently we started adding support for it to actually stand-alone as it's own theme as well, which is where the Customizer support came from.

By "header" are you referring to the logo/navigation row, or the full hero section? There currently isn't a way to remove either without modifying the CSS, but if I can get an idea of what you're going for we can consider all sorts of ideas. I'll verify what that "Hide Header" checkbox controls.

The Customizer should be able to change the logo, but it may not be working yet. I can see that there isn't an edit symbol on your screenshot for the logo, so I'll have to see if I can kick it to make it work again.

Regarding the search bar, I'll have to see if that search input checkbox is referring to the hero search bar or the one in the footer (or if it's working at all).

Thanks for the feedback, and I appreciate you patients with the Customizer support- it'll get there eventually, but unlike many other WP themes, Nebula will need to support both full-on developers as well as being a stand-alone theme, which means there are extra hoops to jump through so both can coexist.

Good to hear from you!

**Comment by chrisblakley** [comment]
Pushed an update that fixes most of these initial issues, and I'm planning on focusing on more Customizer ideas in the near future. I'm going to close this issue, but feel free to re-open or add more ideas/comments to it (or make a new one).

**Comment by JulianKingman** [comment]
That was quick, thanks! For posterity's sake, "header" was referring to the hero section (there's a checkbox "Hide header" or somethign that I assumed would hide the hero).

**Comment by chrisblakley** [comment]
I'm adding a ton more support for the Customizer, so I'm going to dump a snippet here for future reference:

## Customizer input types:

```php
//...

// radio control
$wp_customize->add_control( 'themename_color_scheme', array(
	'label' => __( 'Color Scheme', 'themename' ),
	'section' => 'themename_color_scheme',
	'settings' => 'themename_theme_options[color_scheme]',
	'type' => 'radio',
	'choices' => array(
		'value1' => 'lite',
		'value2' => 'dark',
	),
) );


// checkbox control
$wp_customize->add_control( 'display_header_text', array(
	'settings' => 'header_textcolor',
	'label' => __( 'Display Header Text', 'themename' ),
	'section' => 'header',
	'type' => 'checkbox',
) );


// select control
$wp_customize->add_control( 'example_select_box', array(
	'label' => 'Select Something:',
	'section' => 'nav',
	'type' => 'select',
	'choices' => array(
		'value1' => 'Choice 1',
		'value2' => 'Choice 2',
		'value3' => 'Choice 3',
	),
) );


// color control
$wp_customize->add_control( new WP_Customize_Color_Control( $wp_customize, 'theme_footer', array(
	'label'	=> __( 'Link Color', 'themename' ),
	'section' => 'themename_color_scheme',
	'settings' => 'themename_theme_options[link_color]',
) ) );


// upload control
$wp_customize->add_control( new WP_Customize_Upload_Control( $wp_customize, 'theme_footer', array(
	'label' => __( 'theme footer', 'themename' ),
	'section' => 'my_footer',
	'settings' => 'themename_theme_options[theme_footer]',
) ) );


// image control
$wp_customize->add_control( new WP_Customize_Image_Control( $wp_customize, 'theme_footer', array(
	'label' => __( 'theme footer', 'themename' ),
	'section' => 'my_footer',
	'settings' => 'themename_theme_options[theme_footer]',
) ) );


// background image control
$wp_customize->add_control( new WP_Customize_Background_Image_Control( $wp_customize, 'theme_footer', array(
	'label' => __( 'theme footer', 'themename' ),
	'section' => 'my_footer',
	'settings' => 'themename_theme_options[theme_footer]',
) ) );


// header image control
$wp_customize->add_control( new WP_Customize_Header_Image_Control( $wp_customize, 'theme_footer', array(
	'label' => __( 'theme footer', 'themename' ),
	'section' => 'my_footer',
	'settings' => 'themename_theme_options[theme_footer]',
) ) );


// textarea control
$wp_customize->add_control( new WP_Customize_Textarea_Control( $wp_customize, 'theme_footer', array(
	'label'	=> __( 'Textarea', 'themename' ),
	'section' => 'my_footer',
	'settings' => 'themename_theme_options[text]',
) ) );

//...
```
