### ISSUE TITLE
Update json_ld_ecommerce() to use OOP Nebula refences

### ISSUE THREAD

**Issue by jefcollier** [chrisblakley/Nebula#1381]
Please update `nebula_option()` to use the `nebula()->get_option()` within the `json_ld_ecommerce()` function located [here](https://github.com/chrisblakley/Nebula/blob/b0e3b6a22610bd0fd68bc4926948a1b953bf1a2e/libs/Ecommerce.php#L168-L180).

**Comment by chrisblakley** [comment]
Good catch. I've fixed this and will push it tonight.
