### ISSUE TITLE
SVG and One-Color logo

### ISSUE THREAD

**Issue by Notamongsheep** [chrisblakley/Nebula#1492]
I've noticed that my posts have the one-color logo even if I have the "use one-color logo" deselected under posts > header.

The issue goes away when I remove my site's svg logo.

Testing:
If I have an SVG custom logo, it shows white on a post even if I have the option deselected.
If I have a PNG custom logo, it shows normal for both.
If I have a colored SVG custom logo and a white one-color svg logo, it shows white even with the option deselected.
If I have a colored SVG custom logo and a colored one-color logo (I know, it's supposed to be white - I did this purely to test it) I still get a white logo on the posts page with option deselected.

If I try to select and deselect the option, it seems it makes no difference. Basically my svg logo on my posts stays white no matter what. It's being overridden by the #logonavcon svg img class.

It seems to me that either the option to have/not have it is either not stored correctly or that it's pulling the wrong image for the logo.

**Comment by chrisblakley** [comment]
Thanks for the info- we're still experimenting with Customizer support so I appreciate the feedback!

**Comment by Notamongsheep** [comment]
You're welcome! =)

**Comment by chrisblakley** [comment]
Fixing this was a two part solution:

I created a new function called `nebula->logo()` that will handle the prioritization of which logo file to use. It will prioritize in this order:
- A custom function that hooks into `nebula_logo` (a image file URL is the expected return)
- Customizer on sub-page when *that* one-color logo checkbox is selected
- Customizer on home page when *that* one-color logo checkbox is selected
- Customizer full color logo
- Child theme logo (SVG or PNG)
- Parent theme logo (DVG or PNG)

Full documentation here:
https://gearside.com/nebula/functions/logo/

With that in place, I completely removed the SVG CSS in the child theme so Nebula now relies entirely on one of the above implementations of a logo to look correct.

Thanks again for bringing this up– sorry it took so long to address.
