### ISSUE TITLE
getVideoData() has been removed from the Youtube API

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1519]
Looks like Youtube removed the function `getVideoData()` from the API... I'm seeing this error now:

```
Uncaught TypeError: e.target.getVideoData is not a function
```

Here's the documentation page: https://developers.google.com/youtube/iframe_api_reference
Looks like `getVideoData()` was removed without any note or update.

We use this to store all videos in an array named by their ID, so we use this function to get the ID. I suppose we could try to move to use the ID of the iframe, but I'd much rather use the actual video ID.

**Comment by chrisblakley** [comment]
Here is another library that ran into this issue: https://github.com/sampotts/plyr/issues/709
Unfortunately, their temporary fix was to just check if that function is available and if not, ignore it... which we can't do as easily.

**Comment by chrisblakley** [comment]
Another option could be to parse the `getVideoUrl()` for the ID at the end of the string. Pretty hacky, but may be necessary.

**Comment by jamesherrieven** [comment]
Hi Chris

I've just suggested a fix RE: Plyr. It might work for you too:

`var ytp=e.target;
if(!ytp.getVideoData){
  for(var j in ytp){
    if(ytp[j].videoData){
      (function(j){
        ytp.getVideoData=function(){return ytp[j].videoData;}
      })(j);
    }
  }
}
`

**Comment by chrisblakley** [comment]
Thanks for that snippet. I'll keep it in mind while we see if we'll hear anything from Google. I'd really like to avoid looping through the whole object if possible (and my other fear would be if they remove the nested `videoData()` function too), but we'll see how it goes.

**Comment by jamesherrieven** [comment]
Sure, they may well remove the "videoData" object, but it's more likely they'll add the "getVideoData" method back in - this has happened a few times previously... so you have to assume it's just a mistake!

As a fallback (and given you are only really interested in the video ID) you might want to look at checking the "getDebugText()" method as part of an alternative logic branch...

**Comment by chrisblakley** [comment]
Yeah that's a good thought, and I hope you're right that it comes back. I've got my implementation fixed with parts of your ideas in there too. Thanks for sharing!

**Comment by gusper** [comment]
FWIW, it looks like it's back now. :)

**Comment by chrisblakley** [comment]
That's great to hear- thanks for the update!
