### ISSUE TITLE
Something is wrong with the nebulaVideos object

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1546]
At least in Youtube we're seeing this error:

```
Cannot set property 'title' of undefined
```

It has something to do with `nebulaVideos[id]` around like 3589 in main.js. Maybe the ID isn't properly detected anymore?

Test it here: https://gearside.com/nebula/functions/video_meta/

**Comment by phgjoe** [comment]
https://github.com/chrisblakley/Nebula/blob/master/assets/js/main.js#L3557

should be 
var id = e.target.getVideoData().video_id;

**Comment by chrisblakley** [comment]
Ok so this *was* caused by the Youtube API being changed. `getVideoData()` is not a truly supported method, so it tends to change without warning.

I've made 2 new functions to get the Youtube video ID and title. Now if the API changes it shouldn't trigger an error. I'll make documentation pages for them and then close this issue.

**Comment by chrisblakley** [comment]
https://gearside.com/nebula/functions/nebulagetyoutubeid/
https://gearside.com/nebula/functions/nebulagetyoutubetitle/
