### ISSUE TITLE
Servers without an international version of PHP are unable to log in to WP Admin.

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1586]
On user login submit:

> Fatal error: Uncaught Error: Call to undefined function locale_accept_from_http() in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Utilities/Analytics.php:292

The **locale_accept_from_http()** function doesn't exist in non-international versions of PHP. If a user is running on server who's host doesn't have a PHP-intl installed (of if the user installed a non-intl version), they will be unable to log in. Logic around this?

Tough to test, edge case. I had a non-intl PHP installed on my server so this popped up. I should have come up with a solution before updating PHP on my server, sorry.

**Comment by chrisblakley** [comment]
Nice find! I can look into this, thanks.

**Comment by chrisblakley** [comment]
I think this should fix it:

```php
//...
'ul' => ( class_exists('Locale') )? locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE']) : '', //User Language
//...
```

I'll include it with the next push.

**Comment by chrisblakley** [comment]
Should be fixed with https://github.com/chrisblakley/Nebula/commit/95ce73e540b7837fe68b7d4482d9f0de11fce97f
