### ISSUE TITLE
SCSS does not regenerate when visiting /wp-login.php

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1587]
The SCSS for the login page _(login.scss)_ (re)generates CSS when a user hits the /wp-admin URL first, but not when directly visiting wp-login.php

**Comment by chrisblakley** [comment]
Only logged-in users can trigger Sass to re-process (so if the style.scss was edited, but then an admin did not view the page it would not re-process when anonymous visitors viewed the site). If a user is logged-in and then views wp-login.php it *should* trigger a re-process, but otherwise would not.

I'm open to ideas if we want to improve it (like maybe allowing Sass to process if `is_dev()` is true (I don't *think* it does that currently).

**Comment by chrisblakley** [comment]
Ok now I remember exactly what's going on. I did this specifically for performance reasons.

Nebula has to loop through every file in the scss directory and check the date (and some other things) for each one. To shave off some time, I do the following:

- Skip wireframing styles if the mode is disabled
- Skip the entire /dev directory if dev mode is disabled
- Skip admin files (`login`, `admin`, `tinymce`) when viewing the front-end

Checking is viewing the admin area is easy- we just use (a Nebula alias of) `is_admin()`; however, checking for the login page is actually not very straightforward, so I just lump it in with the rest of the admin pages.

The code specifically is this right here:
```php
$is_admin_file = !$this->is_admin_page() && in_array($file_path_info['filename'], array('login', 'admin', 'tinymce')); //If viewing front-end (including login page), skip WP admin files.
if ( $is_wireframing_file || $is_dev_file || $is_admin_file ){
	continue;
}
``` 
From this file: https://github.com/chrisblakley/Nebula/blob/master/libs/Utilities/Sass.php#L146-L154

We could discuss changes to this behavior, or if attempting to detect the login page would be beneficial we could look into that, too.

**Comment by chrisblakley** [comment]
After all that, I updated the `is_login_page()` function to include the more advanced detection and then added that to the above conditional. So now on the login page it will re-process admin files.
