### ISSUE TITLE
Breadcrumbs URL not correct after changing custom post type archive slug

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1594]
Using **Custom Post Types UI** plugin.

If you change the CPT UI setting for "_Has Archive > Slug to be used as archive URL"_ setting for a custom post type, the breadcrumb nav links still return the original unmodified custom post type slug.

**Comment by chrisblakley** [comment]
Here is how I refactored it:

```php
//...
$slug = $post_type->rewrite;
if ( is_string($post_type->has_archive) ){ //If the post type has a custom archive slug
	$slug['slug'] = $post_type->has_archive; //Replace slug with the custom archive slug string
}
//...
```

I'll push it with the next commit. Closing now, but we're reopen if there are other problems.

**Comment by patphg** [comment]
`has_archive` is just a boolean `true` if the post type has an archive page. With that code, I think it will replace `$slug['slug']` with `true` if an archive page is enabled but no custom slug is set.
