### ISSUE TITLE
PHP Notices in the user settings when WP_DEBUG is defined as true.

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1595]
![screen shot 2018-02-23 at 5 13 18 pm](https://user-images.githubusercontent.com/5795308/36619489-0326aaee-18bd-11e8-8562-5485039ff3cd.png)

**Comment by patmcneil** [comment]
> **Notice:** Undefined offset: 1 in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php on line 142
> 
> **Notice:** Uninitialized string offset: 0 in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php on line 164
> 
> **Notice:** Undefined offset: 1 in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php on line 142
> 
> **Notice:** Uninitialized string offset: 0 in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php on line 164

**Comment by chrisblakley** [comment]
This one has to do with the Notable IPs list. Was there anything in that Nebula Option for your site?

Here's the snippet in question:
```php
foreach ( $notable_ip_lines as $line ){
	$ip_info = explode(' ', strip_tags($line), 2); //0 = IP Address or RegEx pattern, 1 = Name

	$notable_pois[] = array(
		'ip' => $ip_info[0],
		'name' => $ip_info[1]
	);
}
```

**Comment by patmcneil** [comment]
I've got nothing in the notable IPs section. I got around this by just adding a simple check:

````
if( $notable_ip_lines[0] ){ 
  // bla bla bla
}
````

**Comment by chrisblakley** [comment]
Ok I've got a similar fix in. I'm closing this, but if it doesn't do the trick please re-open.
