### ISSUE TITLE
PHP Notices on 404 page when WP_DEBUG is defined as true

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1596]
> **Notice:** Trying to get property of non-object in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Functions.php on line 2899
> 
> **Notice:** Trying to get property of non-object in /home/saltychimpracing/public_html/wp-content/themes/Nebula-master/libs/Functions.php on line 2910

**Comment by chrisblakley** [comment]
The attempted URL that is triggering the 404 page for you must match (or be similar) to an actual post's slug. This has to do with the way Nebula runs a query using the attempted URL as search keywords, so I'm curious why this error is triggering because that object is being checked for existence beforehand.

```php
if ( !empty($error_query->posts) && $slug_keywords === $error_query->posts[0]->post_name ){
	global $error_404_exact_match;
	$error_404_exact_match = $error_query->posts[0];
}
```

**Comment by patmcneil** [comment]
The error moved to line 2904 after an update, probably some code moving around.

The problem is that global $post variable is NULL. To get around it I am simply checking if $post is set and doing everything that requires it inside of some logic.

````
if( isset($post) ){
	$parents = get_post_ancestors($post->ID);
	foreach ( $parents as $parent ){
		if ( !empty($parent) ){
			$classes[] = 'ancestor-id-' . $parent;
		}
	}
	foreach ( get_the_category($post->ID) as $category ){
		$classes[] = 'cat-id-' . $category->cat_ID;
	}
}

**Comment by chrisblakley** [comment]
Ok, I've added your fix in as well as added  a `!is_404()` to the conditional above it too. Should be fixed with the next push. Feel free to re-open if it isn't.
