### ISSUE TITLE
Add a warning for if the child theme is active, but missing meta graphics

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1605]
If the child theme is the active theme, but it is missing the files inside the `/meta/` directory (check for the Open Graph image) trigger a warning. Maybe check for several images Twitter, Open Graph, and favicon(s)?

**Comment by ismaelharunid** [comment]
I have no meta directory in the nebula child directory, only in nebula master.  This from the Nebula-master.zip.  Honestly, everyone needs to really pull their head out of their work when writing instructions or packaging things.  The developer will assume 10000 things that no one would know.  Yes we figure things out but simple thingss like including full an complete instructions, packaging to end use, etc... will greatly help.  You're not the only one, most everyone is like this.  But I do understand this is all free, and thank you.  I don;t mind the work, just I would like to spend it on problems that are not general use problems.  
In conslusion just put that you need to copy the meta directory also, would be a valid fix.

**Comment by chrisblakley** [comment]
I have clarified the warning and will add a note in the installation instructions.
