### ISSUE TITLE
Updating localstorage data for Contact Form 7 crashes IE 11

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#1711]
Commenting out this line seems to fix the issue for Contact Form 7 v5.0.2: https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#L1981

**Comment by chrisblakley** [comment]
[This is interesting](https://stackoverflow.com/questions/21155137/javascript-localstorage-object-broken-in-ie11-on-windows-7), but we're seeing this happen on Windows 10.

**Comment by terencehoverter** [comment]
okay, I don't think it has to do with Line 1981, rather [Lines 1986-1993](https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#L1986-L1993)

**For the lazy:**
```js
nebula.dom.window.on('storage', function(e){
	jQuery('.wpcf7-textarea, .wpcf7-text').each(function(){
		if ( !jQuery(this).hasClass('do-not-store') && !jQuery(this).hasClass('.wpcf7-captchar') ){
			jQuery(this).val(localStorage.getItem('cf7_' + jQuery(this).attr('name'))).trigger('keyup');
		}
	});
});
```

**More specifically this line here:** 
```js 
jQuery(this).val(localStorage.getItem('cf7_' + jQuery(this).attr('name'))).trigger('keyup');
```

**Comment by terencehoverter** [comment]
**Contextual Notes:**
- This event is being triggered twice in IE 11 for me
- I can not get the event to trigger in Chrome

**Comment by chrisblakley** [comment]
I can recreate this now in IE11. I can see the infinite loop on the `storage` event.

**Comment by chrisblakley** [comment]
I'm not in love with this solution, but this isn't a flagship feature. This simply disables localstorage on IE11:

```js
var isIE11 = !!window.MSInputMethodContext && !!document.documentMode; //Check for IE11
if ( !jQuery('.wpcf7-form').length || isIE11 || jQuery('.ie').length ){
	return false;
}
```
