### ISSUE TITLE
nebula.dom undefined in IE 11

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#1712]
Works if you substitute `nebula.dom.window` with `jQuery(window)`

Only used four times in the master javascript file:
- [Line 967](https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#L967)
- [Line 990](https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#L990)
- [Line 2257](https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#2257)
- [Line 2276](https://github.com/chrisblakley/Nebula/blob/master/assets/js/nebula.js#2276)

**Comment by chrisblakley** [comment]
I wonder if there is something else possibly preventing the nebula.dom.window from being defined- all it's doing is caching the selector. Maybe it is being called before it is being cached?

**Comment by chrisblakley** [comment]
If its the whole `nebula.dom` object then there is something running using the object before it is defined. Let's see if we can figure out what is getting called before it's loaded and see if we can fix whatever that is.

**Comment by terencehoverter** [comment]
> If its the whole `nebula.dom` object then there is something running using the object before it is defined. 

I think it is this. I was in the middle of updating the initial issue but yes, it is pretty much breaking everywhere nebula.dom is used. When I run `console.log(nebula);` in Dev Tools it returns the correct object in addition to an `undefined `notice (regardless of browser), see below. 

**Chrome:**
![image](https://user-images.githubusercontent.com/30500449/42849000-84a767e0-89ef-11e8-933d-b4b2dc86f0a0.png)

**IE 11**
![image](https://user-images.githubusercontent.com/30500449/42849027-9ada6bc0-89ef-11e8-950d-cc34d6593587.png)

**Comment by chrisblakley** [comment]
Hmm from those logs it appears that everything is working (I can see that `nebula.dom` is full of jQuery objects in both screenshots). When does it trigger an error in IE11?

I can boot up IE11 in a few minutes to look into this too.

**Comment by chrisblakley** [comment]
For some reason in IE11 (whatever specific version this was) was triggering window load before DOM ready. I guess this is a bug in jQuery 3.1.0...

The solution was to revert to an earlier version of jQuery. Now the decision will be to revert for everything or just IE11...

**Comment by chrisblakley** [comment]
Good conversation happening here: https://github.com/jquery/jquery/issues/3194

jQuery 3 makes the `ready` and `load` states asynchronous so `load` *could* trigger before `ready`.

I think for the time being, I'm going to revert to jQuery 2.2 to always guarantee that the cached selectors are set. We could also call `cacheSelectors()` from inside both the `ready` and `load`...
