### ISSUE TITLE
How is Google finding author archive links (particularly to admin authors)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1731]
Sometimes an admin author username will appear in Google Search Console which means that it is able to find those links. I'm not sure where it is seeing that- maybe in the Yoast sitemap?

- [ ] I'd like to try to disable that along with all the other `author_bios` checks Nebula does.

- [x] I also want to add a pre-made hook into `nebula_no_author_redirect` in `nebula_child.php` so that the "About Us" page permalink can be set- since this is something Nebula can not simply figure out so it does a search for "about".

**Comment by chrisblakley** [comment]
There is an `author_sitemap.xml`: /author-sitemap.xml

**Comment by chrisblakley** [comment]
Yoast has a "Author archives" option that, when enabled, adds the above sitemap. I added a note in Nebula about it, but there isn't really anything more I can do.

**Comment by chrisblakley** [comment]
This is happening quite often. I want to find a way for Nebula to set this option to off by default.

**Comment by chrisblakley** [comment]
Per @jefcollier

```php
// set Yoast Author posts to no-index
function disable_author_post_indexing() {
  if(is_plugin_active('wordpress-seo/wp-seo.php')){ // 'Yoast SEO' | 'wordpress-seo'
    WPSEO_Options::set( 'noindex-author-noposts-wpseo', true );
  }
}
add_action( 'admin_init', 'disable_author_post_indexing' );
```

I've added it to Nebula. I'll do a couple tests and then push to commit.

**Comment by jefcollier** [comment]
We've added a slightly modified variant to this:
```php
// set Yoast Author posts to no-index
function disable_author_post_indexing() {
	if(is_plugin_active('wordpress-seo/wp-seo.php')){
		WPSEO_Options::set( 'noindex-author-noposts-wpseo', true );
	}
}
add_action( 'admin_init', 'disable_author_post_indexing' );
```
I'd like to link to the code block whene/where it's actually implemented within Nebula Master.

**Comment by chrisblakley** [comment]
I actually moved it one more time since we talked to piggy-back on another Yoast override I was doing in the WP admin. Here's where it ended up:

https://github.com/chrisblakley/Nebula/blob/master/libs/Admin/Admin.php#L1142-L1147

I also changed the option to disable _all_ author options in Yoast.
