### ISSUE TITLE
Some plugins have high RIPS CodeRisk score. Consider alternate plugins.

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1733]
These plugins have a higher than 0 RIPS CodeRisk score (out of 100 being the worst):
- https://coderisk.com/wp/plugin/admin-menu-tree-page-view (100)
- https://coderisk.com/wp/plugin/ewww-image-optimizer (31)
- https://coderisk.com/wp/plugin/p3-profiler (14)
- https://coderisk.com/wp/plugin/updraftplus (14)
- https://coderisk.com/wp/plugin/w3-total-cache (29)
- https://coderisk.com/wp/plugin/wordfence (13)
- https://coderisk.com/wp/plugin/wp-mail-smtp (2)
- https://coderisk.com/wp/plugin/wp-optimize (8)
- https://coderisk.com/wp/plugin/wordpress-seo (1)

More information: https://coderisk.com/about

For the ones that are lower than 30 there isn't a concern, but worth looking into to see if there are better alternatives out there (especially for the lesser-used and niche plugins).

**Comment by chrisblakley** [comment]
Found this too regarding 404-to-301 (from 2016): https://www.wordfence.com/blog/2016/08/404-301-plugin-considered-harmful/

**Comment by chrisblakley** [comment]
Made some support topics for the highest two plugins:
- https://wordpress.org/support/topic/this-plugin-has-a-worryingly-high-coderisk-rips-score/
- https://github.com/Joel-James/404-to-301/issues/45

I'm going to keep the 404-to-301 plugin bundled, but I'll probably stop bundling the Admin Menu plugin at least until the security vulnerabilities are fixed.

**Comment by Joel-James** [comment]
@chrisblakley No idea how they calculate this score. At least they should list out the issues IMO. I have registered as a maintainer in their site but the plugin ownership verification is not working.

**Comment by Joel-James** [comment]
**404 to 301** scores are updated
