### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by brattic** [chrisblakley/Nebula#1818]
PHP Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in nebula.php on line 27

This is what I get via WP-CLI when I run commands and Nebula theme is enabled.
Tested against PHP v7.2.14 & v7.1.26

**Comment by chrisblakley** [comment]
Ok– thanks for report regardless. If you run into any WP CLI conflicts don't hesitate to add a new issue- I have not tested with that a whole ton.
