### ISSUE TITLE
IE 11 Gutenberg Bug

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#1821]
Getting a Syntax Error in [admin.js on line 263](https://github.com/chrisblakley/Nebula/blob/ad083e1be7e60c539f00236704a4073c6a425573/assets/js/admin.js#L263)

Issue is causing the Gutenberg editor to get cut off and making any content in the Gutenberg inaccessible.

**Comment by chrisblakley** [comment]
Ah yep that makes sense since fetch is unavailable in IE11. I'll take care of that.

**Comment by chrisblakley** [comment]
We can try updating the conditional to this:
```
typeof fetch === 'function' && !window.MSInputMethodContext && !document.documentMode
```

My guess is that there is a polyfill in one of the plugins (maybe ACF) that actually defines `fetch` as a function.

I still want to figure out why that functionality is even running outside of the dashboard, though.

**Comment by chrisblakley** [comment]
The problem was that IE11 saw the arrow functions and triggered a syntax error so the conditionals were irrelevant. I've updated the function to use older `function()` calls instead.

**Comment by chrisblakley** [comment]
Looks like the problem where Gutenberg is being cut off is a problem inside both ACF and Yoast in IE11.

**Comment by terencehoverter** [comment]
Here is the temporary fix I used:
```php
add_action('admin_head', 'ie11_metabox_fix');

function ie11_metabox_fix() {
  echo '<style>
	body.wp-admin .edit-post-layout__content{display: block;}
  </style>';
}

```

**Comment by chrisblakley** [comment]
Just a quick update to add the IE11 check:

```php
//IE11 temporary Block Editor conflict fix (ACF, Yoast)
add_action('admin_head', function(){
	if ( nebula()->get_browser() == 'internet explorer' ){
		echo '<style>body.wp-admin .edit-post-layout__content {display: block;}</style>'; //This forces the height of the block editor preventing lower metaboxes from overlapping
	}
});
```
