### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get()

### ISSUE THREAD

**Issue by czaczawik** [chrisblakley/Nebula#1838]
At fresh WP install after Nebula activation a have got error when i trying to login into backend:
`Fatal error: Uncaught Error: Call to a member function get() on boolean in /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php:54 Stack trace: #0 /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/libs/Admin/Automation.php(8): Nebula->is_nebula() #1 /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/libs/Admin/Admin.php(18): Nebula->automationhooks() #2 /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/nebula.php(95): Nebula->AdminHooks() #3 /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/nebula.php(50): Nebula->hooks() #4 /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/nebula.php(130): Nebula::instance() #5 /home/klient.dhosting.pl/xxxxx/public_h in /home/klient.dhosting.pl/xxxxx/public_html/wp-content/themes/Nebula-master/libs/Utilities/Utilities.php on line 54`

Can someone tell me what i should to do with this issue?

**Comment by chrisblakley** [comment]
Thanks for the report- I'll look into this right away.

**Comment by chrisblakley** [comment]
I've pushed a fix for this. Thanks again for the report- I really appreciate it!

If that doesn't work, feel free to re-open this issue.
