### ISSUE TITLE
Excerpt Bug

### ISSUE THREAD

**Issue by xcibe95x** [chrisblakley/Nebula#1855]
Wanted to change the excerpt "Read More"
After setting a custom one, it dissappeared completely or would show the excerpt lenght number instead.
I am from the phone now and will post screenshots and more informations later today.
Right now it shows only the post full lenght.

https://cibe.playconstraints.com/

**Comment by chrisblakley** [comment]
Thanks for bringing this up. If you could share the PHP snippet you were using that would help diagnose this as well.

**Comment by xcibe95x** [comment]
The problem presented using the customizer, since then i have been unable to get it back to default even when cleaning both the textboxes, i'm not a php expert so i didn't managed to find a solution and didn't edited any of the php parts, just some html
![nebula](https://user-images.githubusercontent.com/19245385/55669863-d4269c80-587c-11e9-97c6-a812a7f6564d.png)

**Comment by xcibe95x** [comment]
Update: I made some progress.
on /libs/Functions.php 

'more' => get_theme_mod('nebula_excerpt_length', 'Read More &raquo;'),
This line is set to show the lenght changed it to 
'more' => get_theme_mod('nebula_excerpt', 'Read More &raquo;'),
And now it shows Read More again but still won't use the custom name i set in the customizer.

I also believe the lenght box needs to show the default value and not being only blank if an user wants to know the original value and revert it.

**Comment by chrisblakley** [comment]
Thanks for your research here. Looks like it must have been an oversight on the Customizer option name. Glad you were able to find it!
