### ISSUE TITLE
The foreach to remove "log" level warnings in Admin.php needs to check to see if the warnings array is empty or not

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1860]
As it stands, if there are no warnings, it will try foreaching through false, resulting in the error:

`Warning: Invalid argument supplied for foreach() in /var/www/html/saltychimpracing.com/public_html/wp-content/themes/Nebula-master/libs/Admin/Admin.php on line 550`

To solve this I wrapped the code starting on 550 in a simple check like so:

```
if ( !empty($warnings) ){
foreach ( $warnings as $key => $warning ){
						if ( $warning['level'] === 'log' ){
							unset($warnings[$key]);
						}
					}
				}
```

**Comment by chrisblakley** [comment]
Ok, I see a couple other (minor) weird things here too so I implemented your idea and I also returned an empty array from `check_warnings()` if the option has been disabled, so it *should* always be returning an array of some kind no matter what now.
