### ISSUE TITLE
What can we learn from the PWA Toolkit?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1893]
This PWA starter kit also uses Workbox:
https://github.com/jfadev/jfa-pwa-toolkit

This might be a good resource for getting notifications properly working.

**Comment by chrisblakley** [comment]
https://developers.google.com/web/fundamentals/codelabs/push-notifications/

**Comment by jefcollier** [comment]
TIL: about Chrome Web Server:
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb
