### ISSUE TITLE
Detect anchor links for anchors when the full URL is given.

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#1943]
**Describe the Problem**
The listener for `nebula.scrollTo` listens for clicks on `href^="#"` (starts with #). This works perfectly for "traditional" anchors on the current page e.g. `#anchor`. However, when the page anchor includes the full URL, _and the user is on that page already,_ it does not trigger. E.G. http://website.com/about/#history. I've encountered this when an anchored link on a home page is included as a main nav item (so the anchor can be accessible from subpages).

**Proposed Solution**
The trigger should listen for any `href` which _contains_ a `#` by modifying to `a[href*="#"]`.

`nebula.dom.document.on('click', 'a[href*="#"]:not([href="#"])', function(){ . . .`

**Comment by chrisblakley** [comment]
All set.
