### ISSUE TITLE
DataTables CSS, JS loading should be split into it's own function so it can be overriden

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1956]
Nebula auto-loads the default CSS and JS for DataTables. However, DataTables offers a customization tool which one may choose to include optional extensions and even compatible CSS framework styles: [https://datatables.net/download/](https://datatables.net/download/)

So, if a dev wishes to include alternative CSS and extensions for dataTables, it gets mashed up with the default DataTables stuff pulled in by Nebula.

**Proposed Solution**
Instead of including the DataTables check inside of `nebula.lazyLoadAssets`, split it off into its own `nebula.dataTables` or something which can be overridden in `main.js` like other things.

**Alternative Solution**
idk you figure it out man

**Comment by chrisblakley** [comment]
I think what I'll do is decouple Datatables from Nebula so that it still gets registered but you'll need to enqueue it (or call it lazily via JS) yourself. Nebula will provide the "preferred default settings" that we all typically like but only when requested. That way, no overriding is necessary.

**Comment by chrisblakley** [comment]
The chosen.js library has a similar trigger mechanism that we may want to approach the same way.

**Comment by chrisblakley** [comment]
Ok, this has been done for both libraries. Individual child themes are now responsible for enqueuing/loading and initializing both datatables and chosen.js libraries.

They are registered and localized to JS here:

- nebula.site.resources.scripts.nebula_chosen
- nebula.site.resources.styles.nebula_chosen
- nebula.site.resources.scripts.nebula_datatables
- nebula.site.resources.styles.nebula_datatables

Nebula does not provide default options for Datatables, but does for Chosen.js: `nebula.defaultChosenOptions` (object, not a function)
