### ISSUE TITLE
Consider switching from Yoast SEO to The SEO Framework

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1958]
Duplicate of: https://github.com/chrisblakley/Nebula/issues/1269

Yoast: https://yoast.com/wordpress/plugins/seo/
The SEO Framework: https://wordpress.org/plugins/autodescription/

I'm actually really liking the SEO Framework plugin and how straightforward it is. Still need to play around with it some more to get a full understanding of it, but it seems promising.

**Comment by chrisblakley** [comment]
There is going to be a major update to The SEO Framework very soon, so that could coincide nicely with a Nebula switch: https://theseoframework.com/about/an-introduction-to-a-thousand-changes/

**Comment by chrisblakley** [comment]
Remember that there are a lot of hooks for Yoast functionality (and Nebula fallback functionality). SEO Framework also adds structured data for "Organization" info... which is also provided by Nebula. May need a conditional around that too.

**Comment by degeestster** [comment]
Would very much appreciate integration with TSF. So much better and user friendly compared with Yoast...

**Comment by chrisblakley** [comment]
Version 4.0 has been released.

**Comment by chrisblakley** [comment]
Note: Any logic that checks if Yoast is installed would need to be updated as well (including audits in the companion plugin).

**Comment by chrisblakley** [comment]
Closing this as I'm sticking with Yoast. Will still keep my eye on the SEO Framework.
