### ISSUE TITLE
Translations issues

### ISSUE THREAD

**Issue by jpsthome** [chrisblakley/Nebula#1964]
**Describe the Problem**
I have manged to create a translation file for the theme but it can't translate the "Read More" and the months from Functions.php. I don't want to change it directly on the Functions.php file duo to future updates on the theme. Is there any possibility to make both strings translatable? 

**Steps to Reproduce**
Go to any post type archive page. The date of publication and "Read more >>" link don't aren't translateble.

**Screenshots**
![image](https://user-images.githubusercontent.com/19509037/65153385-09284500-da00-11e9-992b-dfbab3a4844b.png)

**Environment Details**
Device: Desktop
OS: Ubuntu 18.04
Browser: Google Chrome 77.0.3865.75

**Comment by chrisblakley** [comment]
Thanks for noting this– I have wrapped that in a translation function and will push a commit soon!

**Comment by chrisblakley** [comment]
This has been committed. Thanks again.
