### ISSUE TITLE
scrollTo() is conflicting with Mmenu when on-page anchors are used

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1967]
If a Mmenu item uses a hash anchor like `#example`, the Nebula `scrollTo()` function detects that in it's `avoid` variable selector and the returns false. That return false actually prevents the scroll action.

Find an alternative to `return false` here or better yet, just wrap that condition around the entire function.

**Comment by chrisblakley** [comment]
This is awaiting end if IE11 support because it will be revisited after the Mmenu v8 upgrade to see if it is still a problem.

**Comment by terencehoverter** [comment]
Adding this to the mmenu options works for me somewhat... still cant get the body to return to its normal width
```
 onClick : {
    close          : true,
    preventDefault : false,
  }
```

**Comment by terencehoverter** [comment]
@chrisblakley... so I looked into this more. I couldn't get the implementation described in my previous comment to work properly so I went back to mmenu's site and took a closer look at their documentation. 

Would you consider enabling the [pageScroll Mmenu add-on](https://mmenu.frebsite.nl/documentation/addons/page-scroll.html) in the [options](https://github.com/chrisblakley/Nebula/blob/main/assets/js/nebula.js#L5354)?
```js
pageScroll: {
	scroll: true,
},
```

I have tested and this works in Edge properly... I would test IE10 support but it doesn't look like the mmenu works at all for IE10, even on gearside.

**Comment by chrisblakley** [comment]
I would be fine using that as long as:

1. It works with the older version of Mmenu that we use (I think 7.x?)
2. It looks like it's deprecated with Mmenu v8+ so we'd need to figure out what to do when we upgrade

Not worried about IE10 at all, but one we stop supporting IE11 (which my predictions have been off before, but I'm thinking Q1 2021 now) we'll be upgrade to v8 on Mmenu. Until then we'll need this to work in IE11 too.

**Comment by chrisblakley** [comment]
Looked into this a little more tonight and I want to clarify the original problem. This does not return false when the parent element matches the `avoid` variable– it only enters that when it does not match:

![Screen Shot 2021-01-30 at 6 38 15 PM](https://user-images.githubusercontent.com/6349678/106370794-7efa2b80-632b-11eb-8011-5d3d970457c3.png)

So if any parent element is `.mm-menu` then the Nebula `scrollTo()` function completely ignores the click event.

**Comment by chrisblakley** [comment]
I might need a refresher on this and/or stick to the original plan of waiting for Mmenu v8... Just got bored and started looking into it.

I noticed tonight that the `.mobilenavtrigger` element (the hamburger menu icon) triggers the Nebula `scrollTo()` and fits the eligibility to animate the scroll. However that doesn't break the offcanvas menu from working. However, if I add `.mobilenavtrigger` to the avoid string, it *does* prevent Mmenu from working property even though that tells this function to completely ignore the click... I know that wasn't the original issue here, but wanted to note it.

That being said, if there *is* a hash link within the Mmenu menu wouldn't we *not* want to ignore it and allow the scroll animation to scroll the page to that element ID?

Also when IE11 is dead, we'll eventually start using the native `scrollIntoView` function, but I don't think Nebula's `scrollTo()` is going to away because it provides finer control at the moment.

So I'm putting this back on the shelf until IE11 support has ended.

**Comment by chrisblakley** [comment]
With the update to Mmenu v8 tonight I did include @terencehoverter 's finding:
```
pageScroll: {
	scroll: true,
},
```

After this is committed, let's give it a whirl and see how it goes

**Comment by chrisblakley** [comment]
Just confirming that after the update, it was noted that this is still an issue. I'll try to reproduce it myself to help troubleshoot.

**Comment by chrisblakley** [comment]
Mmenu no longer exists so this issue should naturally be resolved.
