### ISSUE TITLE
Media Library item previews are stretched

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1970]
![Screen Shot 2019-10-21 at 10 49 24 AM](https://user-images.githubusercontent.com/5795308/67216045-7d377d80-f3f0-11e9-8360-a7598a5fce2a.png)

The cause of this is that the width of the image is set to 100%. To fix this, simply set to auto.

```
table.media .column-title .media-icon img,
.thumbnail img{
	width:auto;
}
```

There is a note in the Nebula-master admin.scss where this is set that says the 100% is to "Ensure SVG images are sized appropriately" so there could be some fine tuning needed, but I can't find an example of setting it to auto messing up any SVGs.

**Comment by chrisblakley** [comment]
I made this change and tested a few SVGs with no problems, so it'll be pushed with the next commit. Thanks.
