### ISSUE TITLE
"Required" highlighting doesn't work on required checkboxes

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1971]
The helpful "you forgot this" outline on submit hover of a form doesn't apply correctly to required checkboxes. This seems to be fixable purely with CSS.

In the _vendor partial, mark `.nebula-empty-required` as **`!important`,** and add this code beneath it to give the wpcf7 `<span>` block-level styling.

```
.wpcf7-checkbox{
	display:inline-block; padding:4px; border:1px solid transparent; border-radius:3px; transition:all 0.25s ease;
}
```

**Comment by chrisblakley** [comment]
Thanks!
