### ISSUE TITLE
nebula.timer doesn't like when you submit a CF7 form without starting the form first

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1972]
Without interacting with the form, nothing starts the Nebula timer. I think? Then, when you submit the form, the JS doesn't like it.

Or something like that. I don't fully understand the timer. So feel free to improve.

To solve this for my situation I moved the setting of thisEvent.formTime and thisEvent.inputs into their own conditional.

Inside of 
`nebula.dom.document.on('wpcf7submit', function(e){`
and 
`nebula.dom.document.on('wpcf7invalid', function(e){`
I removed `formTime` and `inputs` from being set in the `thisEvent` immediately, and put them right below in a conditional.
```
if( typeof(nebula.timings[e.detail.id]) !== 'undefined' ){
    thisEvent.formTime = nebula.timer(e.detail.id, 'lap', 'wpcf7-submit-attempt');
    thisEvent.inputs = nebula.timings[e.detail.id].laps + ' inputs';
}
```

**Comment by chrisblakley** [comment]
Good find.
