### ISSUE TITLE
Phone number validator does not accept non-US toll free or non-US numbers (in general)

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#1973]
For example: (905) 275-0979  or +43 664 2317575

**Comment by patmcneil** [comment]
If I remove the spaces, the first number works. Ignore spaces (in that case)?

**Comment by chrisblakley** [comment]
The first number is working for me without any changes:

![Screen Shot 2019-10-22 at 7 37 24 PM](https://user-images.githubusercontent.com/6349678/67343480-633a8f80-f503-11e9-8259-afc91c2ee046.png)

The second number is erroring (with or without the `+`) and I'll look into that.

I'm testing on this page: https://gearside.com/nebula/functions/nebulalivevalidator/

**Comment by chrisblakley** [comment]
This is the RegEx pattern that Nebula uses in `nebula.regex.phone`:

```regex
^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$
```

We could modify it to work with international numbers, but I would imagine with all the different combinations of numbers that it would simply turn into a "any number of numbers" pattern.

Our other options would be to expand the object to be something like `nebula.regex.phone.us` and `nebula.regex.phone.intl` or `nebula.regex.phone.uk` or you may need to create your own regex pattern for that– which is supported by the Nebula form validation function (or you could piggyback your own validation as well).

Here's an event listener that could be created to do custom form validation with Nebula:

```js
nebula.dom.document.on('keyup change blur', '.nebula-validate-whatever', function(e){
	var pattern = new RegExp(/whatever/, 'i');

	if ( jQuery(this).val() === '' ){
		nebula.applyValidationClasses(jQuery(this), 'reset', false); //Reset if value is empty
	} else if ( pattern.test(jQuery(this).val()) ){
		nebula.applyValidationClasses(jQuery(this), 'valid', false); //Valid when matches pattern
	} else {
		nebula.applyValidationClasses(jQuery(this), 'invalid', ( e.type !== 'keyup' )); //Otherwise, invalid if not matching pattern
	}
});
```
