### ISSUE TITLE
Breadcrumb issue

### ISSUE THREAD

**Issue by phgjoe** [chrisblakley/Nebula#1988]
Missing a space between breadcrumb and 'Page' 

![image](https://user-images.githubusercontent.com/6304779/76221743-e711c180-61ef-11ea-99d4-9812261d6718.png)

Change to 
echo apply_filters('nebula_breadcrumbs_paged', '&nbsp;(Page ' . get_query_var('paged') . ')', $data);
and you're good to go

**Comment by phgjoe** [comment]
github removed my markup... replace the space before (Page with & n b s p ;

**Comment by chrisblakley** [comment]
Added a `&nbsp;` at least for now. One day I'll figure out what is trimming out the initial space and revisit this... Or maybe it'll stay like this forever.
