### ISSUE TITLE
nebula.cf7Functions replaces all form buttons HTML

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#2024]
The `nebula.cf7Functions` script iterates over _each_ `.wpcf7-form input[type=submit]`, but goes on to address _all_ buttons via jQuery inside the `.no-button` conditional.

A simple fix would be changing references to `.wpcf7-form input[type=submit]` to be `this`.

I.E. 

`jQuery('.wpcf7-form input[type=submit]').replaceWith('<button id="submit" type="submit" class="' + jQuery('.wpcf7-form input[type=submit]').attr('class') + '">' + jQuery('.wpcf7-form input[type=submit]').val() + '</button>');`

changes to:

`jQuery(this).replaceWith('<button id="submit" type="submit" class="' + jQuery(this).attr('class') + '">' + jQuery(this).val() + '</button>');`

This also solves the issue of all cf7 submit buttons on the same page are replaced with the text from the first button in the DOM.

**Comment by chrisblakley** [comment]
Thanks. I've implemented this and it will be included in the next commit.
