### ISSUE TITLE
Add a Nebula Options page to allow dequeuing any/all styles/scripts registered with the website

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2036]
Add a tab in Nebula Options that lists out every single script and style that is registered (core, plugins, themes, everything) and provide an interface to dequeue them.

My initial thought was a `Yes/No` select dropdown, but maybe an input field of post IDs (comma separated) for even better control. If `*` or something is in the field it would dequeue it on all pages.

**Comment by terencehoverter** [comment]
My in-progress WG code
```php

<?php 


add_action('wp_enqueue_scripts', 'disable_CF7_Dependencies');

function disable_CF7_Dependencies() {
	# Dequeue Contact Form 7 Dependencies on the front page
	if ( is_front_page() ) {
		wp_dequeue_script('contact-form-7');
		wp_dequeue_style('contact-form-7');
	}

}


add_action('wp_enqueue_scripts', 'disable_WC_Dependencies');

function disable_WC_Dependencies() {
	// Check if WooCommerce plugin is active
	if( function_exists('is_woocommerce' ) ) {
		// Check if it's any of WooCommerce page
		if( !is_woocommerce() && !is_cart() && !is_checkout() ) {
			## Dequeue WooCommerce styles
			wp_dequeue_style('woocommerce-layout'); 
			wp_dequeue_style('woocommerce-general'); 
			wp_dequeue_style('woocommerce-smallscreen');
			wp_dequeue_style('wc-block-style');

			## Dequeue WooCommerce scripts
			wp_dequeue_script('wc-cart-fragments');
			wp_dequeue_script('woocommerce'); 
			wp_dequeue_script('wc-add-to-cart'); 
		
			wp_deregister_script('js-cookie');
			wp_dequeue_script('js-cookie');
		}
	}
}

add_action('wp_print_scripts', 'disable_wpBootstrapGallery_Scripts');

function disable_wpBootstrapGallery_Scripts() {
	if( is_front_page() ) {
		## Dequeue WP Bootstrap Gallery scripts on the front page
		wp_dequeue_script('wc-cart-fragments');
		wp_dequeue_script('wpbgallery-bootstrap-js');
		wp_dequeue_script('wpbgallery-blueimp-js');
		wp_dequeue_script('wpbgallery-gallery-js');
		wp_dequeue_script('wpbgallery-scripts');
	}
}

add_action('wp_print_styles', 'disable_wpBootstrapGallery_Styles');

function disable_wpBootstrapGallery_Styles() {
	if( is_front_page() ) {
		## Dequeue WP Bootstrap Gallery styles on the front page
		wp_dequeue_style('wpbgallery-bootstrap');
		wp_dequeue_style('wpbgallery-blueimp');
		wp_dequeue_style('wpbgallery-gallery');
		wp_dequeue_style('wpbgallery-style');
	}
}

add_action('enqueue_block_assets', 'disable_wpBootstrapBlock_Dependencies');

function disable_wpBootstrapBlock_Dependencies() {
	if( is_front_page() ) {
		## Dequeue WP Bootstrap Block styles on the front page
		wp_dequeue_style('wp-bootstrap-blocks-styles');
	}
}

add_action('wp_enqueue_scripts', 'disable_DataTables_Dependencies', 327);

function disable_DataTables_Dependencies() {
	if( is_front_page() ) {
		## Dequeue DataTables Block styles
		wp_dequeue_style('dataTables-css');
		## Dequeue DataTables Block styles
		wp_dequeue_script('dataTables-js');
	}
}

```

**Comment by chrisblakley** [comment]
Ok, I've got this actually working already. Thanks for your references.

![Screen Shot 2020-07-10 at 5 05 27 PM](https://user-images.githubusercontent.com/6349678/87202940-93af9d00-c2cf-11ea-86e7-d7f05aecf9b7.png)

As a note– to help the inevitable troubleshooting of why a script or style isn't working, I added a line to the Diagnostics tab as well:
![Screen Shot 2020-07-10 at 5 06 07 PM](https://user-images.githubusercontent.com/6349678/87202993-ac1fb780-c2cf-11ea-9691-fc0ee21b83b5.png)

**Comment by chrisblakley** [comment]
Additional ideas:
- Regex tester like on the custom dimensions (make sure its either a number, comma, space, or `*`)
- Highlight the ones that have value (to make it easier to see)– I already found that it is hard to notice the `*` in there

Also, when you click the "(?)" circles, the option handle is wrong for these since they are stored in their own nested array. So this is incorrect:
![Screen Shot 2020-07-10 at 5 10 24 PM](https://user-images.githubusercontent.com/6349678/87203285-45e76480-c2d0-11ea-8da3-1eb27b390c3c.png)

**Comment by chrisblakley** [comment]
Regex ended up being:
```regex
^(\*)$|^(\d+)(,\s?)*(\d*)$
```

**Comment by chrisblakley** [comment]
I expanded this to allow for function names too. Updated the RegEx to be:

```regex
^(\*)$|^(([0-9a-z!_()]+)(,\s?)*)+$
```

**Comment by chrisblakley** [comment]
Here's what it ended up looking like:

![Screen Shot 2020-07-11 at 1 26 32 AM](https://user-images.githubusercontent.com/6349678/87239132-7d8e0380-c3d9-11ea-9890-3c273a4b2e41.png)

I also added an indicator to the WordPress Admin Bar to verify/notify when Nebula is dequeuing assets on the current page:
![Screen Shot 2020-07-11 at 9 52 56 PM](https://user-images.githubusercontent.com/6349678/87239142-98f90e80-c3d9-11ea-813f-67a65e8c6e60.png)

For developers who want their dequeues to appear here, you can use this new function:
https://nebula.gearside.com/functions/deregister/
