### ISSUE TITLE
no-mobile class on #utility-nav not working

### ISSUE THREAD

**Issue by phgjoe** [chrisblakley/Nebula#2069]
https://github.com/chrisblakley/Nebula/blob/1bb8723eba862d01d4526f7590d3c18f9e2ba2dd/assets/js/nebula.js#L5192

You can see it on widewaters.com 
Suggest changing to 
if ( jQuery('#utility-panel').length && (!jQuery('#utility-nav').hasClass('no-mobile') && !jQuery('#utility-panel').parents('.no-mobile').length) ){

**Comment by chrisblakley** [comment]
Possibly related to #2070

**Comment by chrisblakley** [comment]
All set.
