### ISSUE TITLE
mmenu tabs broken for pages assigned to utility menu location

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2070]
**Describe the Problem**
Mmenu tabs are broken for pages listed in the utility menu location. If you go to a page that is listed in the utility menu and open the mmenu you will notice that mmenu successfully labels the right menu item from the correct mmenu tab **BUT** if you try to navigate to the primary menu tab the utility nav is locked on top. Recreated on two sites before submitting.

**Steps to Reproduce**
1. You will need at least three of the menu locations set: Primary, Utility, Mobile
2. From the front-end, go to a page that is listed in the Utility Menu
3. From that page click and open the mobile menu
4. Attempt to click to the "Main Menu" tab in mmenu

**Expected Behavior**
For mmenu to close the utility nav tab "Other Links" and to show the primary nav tab.

**Screenshots**
Actual:
![bug](https://user-images.githubusercontent.com/30500449/93255942-99f74500-f768-11ea-9e91-26bbee5b6cf7.gif)

Expected behavior (non-utility nav pages):
![expected](https://user-images.githubusercontent.com/30500449/93255951-9cf23580-f768-11ea-90d6-8ae6196b00e6.gif)

**Environment Details**
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Windows 10

**Comment by terencehoverter** [comment]
**Update**
Attempted fix described in Issue #2069 by @phgjoe.

**_A few results from this attempt:_**
- Issue #2069 may be related to the issue but that fix doesn't solve this one. In this case, we still want to show the "Other Links" tab in menu and we also want it to work as it is intended on every page
- I don't think Joe's fix is working properly. At least it wasn't working for TFNYS (WordPress 5.4.2, Nebula 7.1.11.8405), where the bug was originally discovered.

**Comment by terencehoverter** [comment]
**Update**
I analyzed, compared, and contrasted the differences between the two interactions (bugged, expected). I think I have been able to pinpoint this to the `#mm-3` div element.  More specifically, when you click the "Main Menu" navigation tab the classes `mm-panel_opened-parent` and `mm-panel_iconpanel-1` on this div should be removed, but they are not.

**Comment by chrisblakley** [comment]
Interesting. Another note for this thread is that we are using an older version of Mmenu because Nebula has not yet dropped support for IE11. If the resolution is to update Mmenu, we won't be able to do that for a few months at the earliest. #1866

**Comment by chrisblakley** [comment]
The problem is in the configuration where we tell Mmenu to listen for the `current-menu-item` class and when it sees that it automatically starts at that level:

```js
...
classNames: {
	selected: "current-menu-item"
},
...
```

I think for the interim while we wait to upgrade to Mmenu v8 I'm going to disable that configuration and the Mmenu will always start at the top-level panel. Then when we upgrade we can see if this has been resolved.

I'm going to close and push this commit and then make a note in #1866 to watch for this.
