### ISSUE TITLE
Might be missing a closing quote after vimeo width

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2078]
Possible missing syntax on this line. I believe there is supposed to be a closing quote after the width.
https://github.com/chrisblakley/Nebula/blob/70f161ce01c8d0e4fa8d3ea8809f41e9a816ad11/libs/Shortcodes.php#L332

**Comment by chrisblakley** [comment]
Yep– great find. I added this fix and it'll be pushed in the next commit. Thanks.
