### ISSUE TITLE
Unable to download .zip for installation

### ISSUE THREAD

**Issue by PaulHBartley** [chrisblakley/Nebula#2079]
**Describe the Problem**
All links to the installation .zip at https://codeload.github.com/chrisblakley/Nebula/zip/master are returning a **404: Not Found** error.

**Comment by chrisblakley** [comment]
Thanks for the heads-up– that was an unintended side-effect of switching to the `main` default branch.

**Comment by PaulHBartley** [comment]
Ah okay! Thanks

**Comment by chrisblakley** [comment]
I've updated all of the links on the documentation site– I'm not sure how long it would take for the Github to update `codeload`, but hopefully it won't take too long.

In the meantime, https://codeload.github.com/chrisblakley/Nebula/zip/main does work.

Where did you retrieve that link originally? I can see if there is any kind of manual update I can make there (if necessary).

**Comment by PaulHBartley** [comment]
Great - the link you shared works.

At https://nebula.gearside.com/get-started/ in the upper right-hand corner there's a "Download" link that has ".../zip/master" rather than main. I think that was where I originally tried to download it.

**Comment by chrisblakley** [comment]
Ok cool- that has been updated so we should be all set! Thanks for bringing this to my attention!
