### ISSUE TITLE
Update to SCSSPHP beyond 1.4 after variables import bug is resolved

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2088]
Currently, when re-processing Sass files Nebula shows an error that an import file could not be found– in this case specifically the `variables` partial. I've tried changing the config array to test, but then all other import partials trigger an error, so it seems isolated to just the variables partial.

![Screen Shot 2020-11-07 at 7 00 33 PM](https://user-images.githubusercontent.com/6349678/98453860-ceb1c800-212b-11eb-9d94-9bf0337cb275.png)

One above excerpt in real text:
```
[Sass Compilation Error] `/wp-content/themes/Nebula-main/assets/scss/partials//variables` file not found for @import: style.scss on line 16, at column 1 in /wp-content/themes/Nebula-Child/assets/scss/style.scss. This file has been skipped and was not processed.
```

Note in the screenshot that the path it is looking in has a `//` as if it is missing a directory, so maybe this is a clue that maybe it is a library issue?

I did not create an issue in the [SCSSPHP repo](https://github.com/scssphp/scssphp/issues) because I can't verify this is their problem... However, I have not changed anything in Nebula, and when I revert to 1.3 it works fine...

**Comment by chrisblakley** [comment]
Keep an eye on this thread: https://github.com/scssphp/scssphp/issues/271 Looks like there is a PR already so could be resolved as early as the next release.

**Comment by stof** [comment]
Can you try with https://github.com/scssphp/scssphp/pull/278 to see if the issue is solved by that PR ?

**Comment by chrisblakley** [comment]
@stof Unfortunately that PR code does not appear to have solved the above issue. When I switched to that code and re-processed Sass, the same `file not found for @import:` error is appearing as the screenshot above. Thanks for checking in– I'm happy to continue testing as needed!

**Comment by stof** [comment]
@chrisblakley the error message in scssphp corresponding to `%s file not found for @import` is giving the actual import rule present in the scss file in the error message. So do you actually have such path `/home/[redacted]/wp-content/themes/Nebula-main/assets/scss/partials//variables` appearing in your scss file ?

There is a known issue in scssphp 1.4.0 regarding importing absolute paths, which might be the reason of the issue.

**Comment by chrisblakley** [comment]
That is correct– my main stylesheet is located in `/home/.../wp-content/themes/Nebula-main/assets/scss/style.css` and contains (for example):
```scss
@import "variables";
@import "functions";
@import "mixins";
//Among others...
```

Those partials exist in a `/partials/` subdirectory– for example: `/home/.../wp-content/themes/Nebula-main/assets/scss/partials/_variables.scss`.

Here's a screenshot of the directory structure if that helps:
![Screen Shot 2020-12-16 at 1 57 01 PM](https://user-images.githubusercontent.com/6349678/102393640-a5941b00-3fa6-11eb-9906-0d1e16ef4c23.png)

Regardless if this is issue is related to the bug you were originally trying to solve, I appreciate your time, thanks.

**Comment by stof** [comment]
@chrisblakley your issue happens in `wp-content/themes/Nebula-Child/assets/scss/style.scss`, not in `wp-content/themes/Nebula-main/assets/scss/style.css` though

**Comment by chrisblakley** [comment]
> @chrisblakley your issue happens in `wp-content/themes/Nebula-Child/assets/scss/style.scss`, not in `wp-content/themes/Nebula-main/assets/scss/style.css` though

Sorry about that- that was a typo. I did mean style.scss. I have edited my previous post above to correct it.

**Comment by stof** [comment]
@chrisblakley the actual issue is `Nebula-main` vs `Nebula-child`, which means that the content of the file is probably not the one you shared.

**Comment by chrisblakley** [comment]
My bad– I didn't catch that on my phone last night. The content of the child style.scss file is very similar, but uses a variable defined in PHP to locate the parent theme partials directory:

Child theme style.scss:
```
@import $parent_partials_directory + "/variables"; //Parent theme variables first
@import "variables"; //Then child theme variables
@import $parent_partials_directory + "/functions"; //Parent theme functions
@import $parent_partials_directory + "/mixins"; //Parent theme mixins
//And so on...
```

That `$parent_partials_directory` variable ends up being `/home/.../wp-content/themes/Nebula-main/assets/scss/partials/`
It is defined when SCSSPHP is invoked in PHP like this:
```php
require_once get_template_directory() . '/inc/vendor/scssphp/scss.inc.php'; //SCSSPHP is a compiler for SCSS 3.x
$this->scss = new \ScssPhp\ScssPhp\Compiler(); //Note: $this refers to the nebula() class

//Register import directories
if ( !is_array($location_paths['imports']) ){
	$location_paths['imports'] = array($location_paths['imports']); //Convert to an array if passes as a string
}
foreach ( $location_paths['imports'] as $imports_directory ){
	$this->scss->addImportPath($imports_directory);
}

//...some other settings

//Variables
$nebula_scss_variables = array(
	'parent_partials_directory' => get_template_directory() . '/assets/scss/partials/',
	'child_partials_directory' => get_stylesheet_directory() . '/assets/scss/partials/',
	//...some others
);
$this->scss->setVariables($nebula_scss_variables);

//...then it goes on to compile the scss files.
```

The above PHP excerpt is pulled from this file if you want to see the additional lines I skipped over:
https://github.com/chrisblakley/Nebula/blob/main/libs/Utilities/Sass.php#L139

My apologies for the confusion on that.

**Comment by chrisblakley** [comment]
I can confirm that the latest release has resolved this issue. I appreciate everything you all do!
