### ISSUE TITLE
Docs: Incorrect location for add_internal_post_keywords()

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#2094]
https://nebula.gearside.com/functions/add_internal_post_keywords/

**Comment by chrisblakley** [comment]
I think this was actually a deprecated method of adding keywords to posts. Looks like you ended up finding what you were looking for with: `<?php echo get_post_meta($id, 'nebula_internal_search_keywords', true); ?>`

**Comment by chrisblakley** [comment]
FAQ has been updated too: https://nebula.gearside.com/faq/
