### ISSUE TITLE
isMobileBarVisible breaks mMenu in IE11

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2099]
**Describe the Problem**
The isMobileBarVisible conditional that loads MMenu isn't firing in Internet Explorer 11. I believe the issue surrounds the fact that jQuery isn't finding the specified border color that is used to determine if the element is actually visible.

**Possible Solution**
[Adjust this line](https://github.com/chrisblakley/Nebula/blob/main/assets/js/nebula.js#L5271) to work properly cross-browser:
```js
var isMobileBarVisible = ( jQuery('#mobilebarcon').css('border-color') === 'rgba(255, 255, 255, 0)' )? true : false;
```
Adjusting the conditional to look for `border-left-color` seems to fix the issue in most cases. 

There is still an issue when the browser opens up initially at the desktop size. The window has to be resized for mobile twice for this to fire properly, so you may want to look more into that.

**Steps to Reproduce**
1. Go to https://nebula.gearside.com/ in IE11
2. Click on Mmenu
3. It doesn't slide out

**Expected Behavior**
The mmenu to slide out.

**Screenshots**
Nebula on gearside in IE:
![mmenubroken](https://user-images.githubusercontent.com/30500449/102721015-e56c4280-42c5-11eb-88f7-bf75bca67447.gif)

**Environment Details**
Windows 10, Internet Explorer 11

**Comment by chrisblakley** [comment]
Thanks for the heads-up. I've updated that line to include the `border-left-color` like you suggested and will push that commit tonight.

The note about needing to resize twice may be an intermittent issue as that `initMmenu()` function is called after a 250ms debounce on resizing here:
https://github.com/chrisblakley/Nebula/blob/main/assets/js/nebula.js#L106

I'm curious if your fix resolves both problems– we can test again after the push.

**Comment by chrisblakley** [comment]
@terencehoverter We can check if the multiple resizing need is still a problem in IE11 and re-open as needed to address it.

Also crosslinking #1866 as v8 will not be supporting IE11 at all– that will happen at some point in 2021.
