### ISSUE TITLE
Nebula v8.9.5.7626 let bug with IE 11

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2144]
**Describe the Problem**
Not sure if that build number is the last version that Supports IE 11 but there is a ```let``` keyword used on [line 286 of nebula.js](https://github.com/chrisblakley/Nebula/blob/v8.9.5/assets/js/nebula.js#L286).

The temporary fix is to convert to:
```js
for ( var i = 0; i < registrations.length; i++ ){ 
	registrations[i].unregister();
}
```

**Environment Details**
IE 11, Nebula v8.9.5.7626, Windows 10

**Additional Information**
2021 and still fighting Internet Explorer

**Comment by chrisblakley** [comment]
Hmm, I agree that your fix would do the trick, but it is strange that IE11 is looking inside the `if ( 'serviceWorker' in navigator ){` conditional– which should be false in all versions of IE.

I can branch and commit an update to 8.9.5, but it is a little odd to me that this is even a problem.

**Comment by terencehoverter** [comment]
Yeah that part gets me too. Correct me if I am wrong, but I believe the reason why it happens is because IE 11 partially supports the ```let``` keyword but only in certain declarations. I [read somewhere](https://stackoverflow.com/questions/2356830/what-browsers-currently-support-javascripts-let-keyword) that you could format it properly to work in a ```for``` but it doesn't work in the way you would expect.  I suspect the formatting on this is causing a "syntax" error because its.

**Comment by chrisblakley** [comment]
Ok added this fix and also force-disabled theme updates while I was in there. I'll leave this branch active just in case we ever run into any other IE11 issues.

Good catch– thanks for letting me know.
