### ISSUE TITLE
Move Yoast to Bottom

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#2175]
In the spirit of Joe I'm making this feature request usable but as unhelpful as possible.

<img width="468" alt="Screen Shot 2021-08-17 at 4 14 29 PM" src="https://user-images.githubusercontent.com/6305007/129794259-0861f241-3e46-4877-9563-1684e1ee4d7c.png">

**Comment by chrisblakley** [comment]
I have deprioritized the Yoast post metabox. Pray I do not deprioritize it further.

**Comment by patphg** [comment]
![yooooooooooooast](https://user-images.githubusercontent.com/6305007/129905657-eb58e782-d3b9-4865-b969-23f89a57da91.jpg)
