### ISSUE TITLE
Error message: Update failed. The response is not a valid JSON response.

### ISSUE THREAD

**Issue by ladina123** [chrisblakley/Nebula#2182]
**Describe the Problem**
Since I installed the new worpressupdate I can't publish new posts. As soon as I want to insert the blocks (for example image block), the error message appears: Update failed. The response is not a valid JSON response. I have read that the theme (in our case Nebula) can be the reason here, because it is not compatible with the new update.

**Steps to Reproduce**
1. Go to Worpress in "All articles"
2. Click on "Create" and add a block (e.g. image block/gallery)
3. Try to save the article or view the preview
4. See error on the top of the page and that the article was not saved

**Expected Behavior**
Please check if this theme triggers this error message. Tips on how to write the blog posts again.

**Screenshots**
![image](https://user-images.githubusercontent.com/93384544/139434160-5fc4c316-3e0f-46c9-aff0-0a9017eee8f9.png)

**Comment by chrisblakley** [comment]
If you could also provide the version number of Nebula and WordPress (in the lower right of most admin screens) that would be helpful. I know we've run into this back when we first started integrating with the Block Editor due to conflicts with overtightened security.

If there are Nebula updates available, consider updating the theme to latest.

I was not able to recreate this error– but we can look into this further with some additional info– thanks!

**Comment by ladina123** [comment]
Hi @jefcollier 
Thanks for your quick reply.

1. I have no option to diable the Nebula Theme... I can only customize it: ![image](https://user-images.githubusercontent.com/93384544/139638032-bdd0e93b-ba2c-4e7c-88e1-b9eb62797248.png)

2. ![image](https://user-images.githubusercontent.com/93384544/139638882-a425431f-c589-46f8-a89b-b7d3ef1ccf69.png)

Thanks in advance for your help!

**Comment by ladina123** [comment]
Hi @chrisblakley 

Worpress version is 5.8.1 (since the update, the error message appears)
Nebula version is 1.5

Thanks!

**Comment by chrisblakley** [comment]
Ah, thank you for the screenshot and info. That is a different "Nebula" theme that was created by someone else sometime after this Nebula theme. Just from my understanding it was made before the Block Editor, so it seems like it was not updated to support it.

Sorry we won't be able to assist here– you'll need to either reach out to that theme developer or you may need to find a different theme with Block Editor support.
