### ISSUE TITLE
Safari Mobile Search Input Appearance is off

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2195]
**WordPress Version**: WordPress 5.4.2
**Nebula Version**: v9.9.23.350

**Describe the Problem**
The appearance of the mobile search input is off in Safari on iOS. (Tested on iPhone 13 using BrowserStack)

**Steps to Reproduce**
1. Open nebula.gearside.com on any iPhone 13 in Safari

**Expected Behavior**
See Screenshots

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/30500449/155559931-e0e4fb9c-bdb8-44b6-8d53-3d7b6898726a.png)
Reality:
![image](https://user-images.githubusercontent.com/30500449/155558357-e9912ee4-610b-4928-8264-581cd7806aa8.png)

**Environment Details**
**OS:** iOS, v15.1
**Browser:** Safari

**Additional Information**
Bootstrap 5.1.3 applies a `-webkit-appearance` property with a value of `text-field` that targets `[type=search]`. The quick solution to this is to override it by setting `-webkit-appearance: none;` [somewhere here](https://github.com/chrisblakley/Nebula/blob/main/assets/scss/partials/_navigation.scss#L10-L11)

**Comment by chrisblakley** [comment]
`-webkit-appearance: none;` did the trick– thanks for researching that issue!
