### ISSUE TITLE
Consider using a more general search input selector

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#2216]
Right now the nebula search form generates with an `id="s"`

There is a ton of cool JavaScript which is listening and acting on things based on `#s` and triggering a lot of actions.

However, if there is more than one nebula search on the page, i.e. if there is a search bar in the header _and_ the footer, this causes issues.

Consider moving away from ID based selectors and on to something more general like a class or even just `input[name="s"]`

**Comment by chrisblakley** [comment]
This is actually also relevant for #2218 as they fixed it so search widgets don't all have the same ID of `s`, so Nebula's styles will need to update to `input[name="s"]` anyway.
