### ISSUE TITLE
Nebula Options Search not returning refined results

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#2264]
_Version information can be found in the lower right of most WP admin screens_
**WordPress Version**: WordPress 6.3.1
**Nebula Version**:  Nebula 11.4.21.615 

**Describe the Problem**
Searching for an option in the Nebula Options does not return refined results, all options are returned instead (because of an error)

**Steps to Reproduce**
1. Go to... Nebula Options
2. Click in... Search and type an option like "Sass"
3. See results are disappointingly every nebula option to exist
4. See error in the console suggesting regex is not defined in search.js on line 51

**Expected Behavior**
TO BE ABLE TO SEARCH AN OPTION IN THE NEBULA OPTIONS.

**Screenshots**
![image](https://github.com/chrisblakley/Nebula/assets/30500449/fa9fa35f-9f20-45f7-a767-7e1d665b7bbc)
![image](https://github.com/chrisblakley/Nebula/assets/30500449/9c91453e-d32a-4021-a085-b3d43e9dbf48)
![image](https://github.com/chrisblakley/Nebula/assets/30500449/0d2a7166-2438-446f-aa38-fdbd83fac9b2)

**Environment Details**
Windows custom built PC aka Disco-Volante running Windows 10, Latest version of Chrome

**Additional Information**
I have been developing all day and this was the quickest I was able to fill out a bug report

**Comment by chrisblakley** [comment]
Thanks Terry– I'll get this taken care of.

**Comment by chrisblakley** [comment]
The solution here was to change the `let` to `var` inside the try/catch a few lines up from where the error was occurring:

```js
try {
	var regex = new RegExp(value, 'i'); //Keep var here so variable can be used outside of the try/catch without erroring
} catch(error){ //This is an invalid RegEx pattern
	return false; //Ignore this search
}
```

This will be pushed to Nebula, but this should also be an easy retrofit if needing to fix without updating the entire Nebula theme.
