### ISSUE TITLE
Dequeue JS does not with with negated page ID

### ISSUE THREAD

**Issue by patphg** [chrisblakley/Nebula#2273]
In Nebula options, I am using the dequeue JS fields in the advanced section to dequeue a script on ALL pages NOT ID 721 like so:

![Screenshot 2024-01-11 at 11 24 11 AM](https://github.com/chrisblakley/Nebula/assets/6305007/8d594619-dd9c-4c31-a5ce-1a2e9c5f9027)

This appears to have no effect. However if I use, for example, `is_front_page`, it does dequeue the script on the front page, so I know the setting is working in some ways.

I will continue to troubleshoot and update this issue with any findings or fixes.

**Comment by chrisblakley** [comment]
Ah interesting thought– originally the `!` inversion was only intended to be used with function names, but this is a great use case. It has been updated and will be included in the next commit.
