### ISSUE TITLE
More customization needed for FPO forms in wireframing

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#621]
More options are needed for the `fpo_form()` function in wireframing. Clients are getting hung up on the forms not being exactly what they expect. Radio buttons, checkboxes, select options, etc.

I think to be more flexible, `fpo_form()` should be replaced entirely by something like:
```php
fpo_component_start('form');
    fpo_form_start();
        fpo_form('text-field', 'title', 'placeholder');
        fpo_form('text-area', 'title', 'placeholder');
        fpo_form('radio', 'title', false); // false is whether it is checked or not
        fpo_form('checkbox', 'title', false); // false is whether it is checked or not
        fpo_form('select', 'title', $array); // where $array is the list of options
        fpo_form('button', 'title');
    fpo_form_end();
fpo_component_end();
```

etc.

**Comment by chrisblakley** [comment]
My initial thought is to actually consider removing fpo_form entirely...

We could do something like this to make the component:
```html
<?php fpo_component_start('form'); ?>
<form>
<input type="text" placeholder="Name" />
<input type="email" placeholder="Email" />
<input type="submit" value="Send" />
</form>
<?php fpo_component_end(); ?>
```

Only drawback is that wireframing would require more HTML knowledge. Maybe there is a solution that is in between?

**Comment by chrisblakley** [comment]
This is a note that I've started deprecating some wireframing functions and my goal is to trim it down to on the absolutely essential functionality. Then we can revisit how we want to attack the header/footer and/or templating scenarios.
