### ISSUE TITLE
Compatibility Mode Detection with Edge browser (vs. IE11)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#662]
http://gearside.com/nebula/documentation/examples/ie-compatibility-mode-detection/

Come up with a polyfill feature to detect Edge vs IE11.

Also, find a polyfill to detect IE11 vs. IE10 besides pointerevents that doesn't require a custom build of modernizr.
![screen shot 2015-05-30 at 5 39 49 pm](https://cloud.githubusercontent.com/assets/6349678/7899507/1910ba22-06f3-11e5-9f61-da8079d66351.png)

**Comment by chrisblakley** [comment]
Wait for Modernizr 3 to appear on CDN JS and see what default polyfills are available.

**Comment by pmcneil18** [comment]
Here are the IE 10 non-dev modernizr <html> classes

js flexbox no-flexboxlegacy canvas canvastext no-webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize no-borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg no-smil svgclippaths gumby-no-touch

**Comment by pmcneil18** [comment]
.borderimage works!

**Comment by chrisblakley** [comment]
style.css updated.

Need to update http://gearside.com/nebula/documentation/examples/ie-compatibility-mode-detection/ now.
