### ISSUE TITLE
Media query mixin doesn't like how custom query parameters work

### ISSUE THREAD

**Issue by patmcneil** [chrisblakley/Nebula#917]
The media query mixin randomly, and only on some servers, causes the error: 
"Failed to load resource: net::ERR_CONNECTION_RESET" on the (child) theme's stylesheet. This prevents the stylesheet from loading.

The issue stems from the ability to pass a custom query to the media mixin. When the ability is removed, the mixin performs as usual.

**Comment by chrisblakley** [comment]
Here is the current potential fix (from you, just noting it here too):
```
@mixin media($group){
    @each $name, $rule in $all_media_queries {
        @if $group == $name {
            @media #{$rule} { & {@content} }            
        }
    }
}
```

**Comment by chrisblakley** [comment]
This definitely works, but I have no idea why. Have not been able to recreate on my own server yet, so could be a library issue, or a PHP version bug, or (likely) some kind of syntax error within the mixin itself...

Applying this fix for now, but I really want to have the ability to pass custom query sizes.
