### ISSUE TITLE
Programmatic way to preserve Wireframe during theme development

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#983]
The solution must allow us to view both production and wireframe non-destructively. It should also continue to share the same DB. Ideally the solution would be at the theme level so it can be bundled with Nebula. Plugin would be the next best. I'd rather avoid anything above that level, but we can discuss.

Keep in mind this needs to work with child themes as well.

A few options:
- Override the site URL setting in the DB using PHP to point to two different places as needed
- Use the Theme Check plugin to easily toggle between the two.

**Comment by patmcneil** [comment]
Here is how I currently do it. This is not at the theme level and is a hack that must be reversed before launch. This might be a seed of a larger idea, though. This method assumes that Wordpress is installed in the root directory.

1. Create subdirectory in the root dir, _wireframe/_
2. Copy all WordPress files from the root directly into _wireframe/_
3. Create subdirectory in the root dir, _production/_ and copy into it the contents of _wireframe/_
4. Next, create and update the URIs for both versions **on the fly**, [using a variation of this method](http://codex.wordpress.org/Moving_WordPress#If_You_Have_Accidentally_Changed_your_WordPress_Site_URL).
5. In _wireframe/wp-login.php_ AND _wireframe/wp-blog-header.php_, find the line `require( dirname(__FILE__) . '/wp-load.php' );` After that line, paste the following: `update_option('siteurl', 'http://domain.name/wireframe' ); update_option('home', 'http://domain.name/wireframe');`
6. Save both and visit _wp-login.php_. It should correctly direct you to _wireframe/wp-login.php_
7. Log in, and **re-save** the permalinks settings in Settings > Permalinks to regenerate .htaccess
8.** Repeat steps 4–7**, but swap _production/_ with _wireframe/_.

Now, whenever a page (or the login page) is loaded, the `update_option()` function is executed, swapping the siteurl and home strings. This happens before anything else that references those strings.

**Comment by patmcneil** [comment]
To make things simpler in this method, we could find out what in _wp-load.php_ includes `update_option()` and just run the updates immediately after it, inside of _wp-load.php_, insead of tacking it on after the two instances where it is `require_once()`'d.

**Comment by chrisblakley** [comment]
[Here is a list of WordPress hooks we can look into before editing core files.
](https://codex.wordpress.org/Plugin_API/Action_Reference)

I'm not excited about duplicating WP Core files, but the idea could work with duplicating the theme. Let's try the [Theme Check](https://wordpress.org/plugins/theme-check/) plugin and see where that takes us.

Maybe we consider the Nebula Wireframing is a plugin and not a theme option? Then we can activate/deactivate separately. I don't know how we'd be able to preserve a wireframe with this method, though... Theme Check might be our easiest solution.

**Comment by chrisblakley** [comment]
Ok, Multiple Themes plugin will work. Here's what needs to happen:

- Activate the Multiple Themes plugin (and do nothing with the settings)
- In Nebula Options, enable Wireframing.
 - In the back-end, Nebula will modify the necessary settings in ```nebula_wireframing.php``` for the Multiple Themes plugin.
  - Using ```?wireframe``` or something along those lines will show the wireframe
  - Using anything else will show the production site.
- Modify the Wireframing menu in the Admin Bar to:
 - "Wireframing" (Link to Nebula Options or Nebula Documentation)?
  - View Wireframe (if plugin is activated, otherwise "Wireframe Unavailable")
  - View Production Site
- If plugin is not found/activated, then show a warning in the WP Admin that wireframing is enabled, but plugin is required.

**Comment by patmcneil** [comment]
Check out line 314 of _admin-sections.php_ of the Multiple Themes plugin, and inspect the query keyword field on the themes settings for more info.

**Comment by chrisblakley** [comment]
I updated the options page to use select menus for available themes.

Would love to remove the need for the "Production Theme" option by just using the current theme directory, unfortunately there doesn't seem to be a simple way of getting the current theme directory name. With ```wp_get_themes()``` the directory name is used as the array key, but in ```wp_get_theme()``` the directory name is unavailable... :(
