### ISSUE TITLE
Optimize JS with some Chrome dev tools tricks

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#992]
- [x] Time JS functions: https://umaar.com/dev-tips/99-line-level-profiling/
 - [x] Start and End too: https://umaar.com/dev-tips/83-console-time/
- [x] Log times of various events: https://umaar.com/dev-tips/84-console-timestamp-timeline/
- [ ] Check remote rendering time by domain: https://umaar.com/dev-tips/67-timeline-costly-groupings/
- [ ] Check frame times for animation issues: https://umaar.com/dev-tips/54-long-frame-times/

**Comment by jefphg** [comment]
@Blakes: can you crash course me in this sometime?

On Thu, Apr 7, 2016 at 11:18 AM, Chris Blakley <notifications@github.com>
wrote:

>
>    - Time JS functions:
>    https://umaar.com/dev-tips/99-line-level-profiling/
>       - Start and End too: https://umaar.com/dev-tips/83-console-time/
>    - Log times of various events:
>    https://umaar.com/dev-tips/84-console-timestamp-timeline/
>    - Check remote rendering time by domain:
>    https://umaar.com/dev-tips/67-timeline-costly-groupings/
>    - Check frame times for animation issues:
>    https://umaar.com/dev-tips/54-long-frame-times/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisblakley/Nebula/issues/992>
>



-- 
*PinckneyHugoGroup*

*Jef Collier | Sr. Digital Manager *
760 West Genesee Street, Syracuse, NY 13204
315.478.6700 | jef@pinckneyhugo.com

**Comment by chrisblakley** [comment]
Entirety of main.js renders in 233ms. Not going to look into overhauling anything for optimization purposes at this time.
